apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../flux-system/buxfer-sync-secret.yaml
  - ../flux-system/deskbird-booking-secret.yaml
  - ../flux-system/github-app-secret.yaml
