apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-values
  namespace: cattle-system
data:
  values.yaml: |
    hostname: rancher.sargeant.co
    replicas: 1
    bootstrapPassword: "admin"
    # Node selector for main Rancher pods
    extraNodeSelectorTerms:
      - matchExpressions:
          - key: type
            operator: In
            values:
              - pi