apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-credentials
  namespace: observability
spec:
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: slack-credentials
    creationPolicy: Owner
  data:
    - secretKey: slack-bot-token
      remoteRef:
        key: slack-bot-token
