apiVersion: ENC[AES256_GCM,data:mio=,iv:DPCV7yC96KTIWjUxqzhJO/oV6qWtE3cp5ua6ng1mgIg=,tag:AlAqZEfeiGRk2MHMS/Pecw==,type:str]
kind: ENC[AES256_GCM,data:crVbwKU0,iv:YShG7kywhZHc7jUWAgGoQr4G0CAqFp/Ctk8oamQCkNE=,tag:2d2aFFZ6+q65pdYj/OEXYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2MvdFKYXWg==,iv:EAlRvUaOc0fMnku18scmpqcigRX6radXbjb6zk80WrQ=,tag:XP09pPBqJdxVKIXtaqLlgg==,type:str]
    namespace: ENC[AES256_GCM,data:2CZBBaEibfQ=,iv:yChhcI+VFVtvaUf3h8qEAYhWtwxFCY+Dy95k2IURsWo=,tag:jEyrlfQncDAxyZpOl7TB3A==,type:str]
type: ENC[AES256_GCM,data:wJCKh8mP,iv:7f6kyYOlkYsbUJvwJCRtgxzRH7aZmtxsGw3zJB6xcA4=,tag:s8ykQkFJCJVtsHYzvdFoGQ==,type:str]
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:OBsYGMCa2+YVx3IELrXZ0KoEHlYnNPrrIsFAWidx4gSXV2ptAYQ4Z9lfE2I=,iv:UAB6I3uLF94K/G+mjd5Mn76tzGPbsGHE9AfvD+l+DYk=,tag:tcmvKnjgjHcjZkrCSXSx8g==,type:str]
    wordpress-user: ENC[AES256_GCM,data:AnOK6L0s2iWn,iv:WRjUOW0UuGBDeo+Dou2cLyBZKg7rVInWLVnCmZVpHSQ=,tag:SbmG9uT+wheAJBez3Ox6dg==,type:str]
    wordpress-password: ENC[AES256_GCM,data:UL6ojrsrN16B/ZtRz3vMRE0+hIkeRTk0FlD/8KYOjE9XjnH0AzaXF7Fotb8=,iv:/S1ri4hNEGOOjz6v2joQDk+69t3U/5OSrOuS7Szu5WE=,tag:m8pasjUMFXmBnvuEo2aVrg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZUc5bkE1ZUpXdjhlcDV2
            K2RtTXBKbnhtTTh1N0F0RUtSaEtQMWZGb3prCnRTMnFzY05JOW51em1pMkFodSta
            M3A4K204Y2xvcnNtRFpVU0NTTkxYNGMKLS0tIDliWlRUUFJzRDNSUm1aOVRENWxw
            ZHpicDNxMzJoUzRUUXZQbVJtQ0ZRL1kKxINXvjUcTPdpF+zG34/J86ncsajbXDMY
            jHPfEGsCThRZFow6mS2CgrQCjkL8AKXV3Y4CDUXYz+AxBsXoRaNCLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:13:51Z"
    mac: ENC[AES256_GCM,data:XXQ2pj5HeU+9QQI7EMRHaC3OIeUCBag3nK6RNTG0CpavT/ZauJsk/qWBjEqU1uupftJ0WrnvxdTaBFPPjOzF7FHlftPN/otwmNvASP5aQtDrmpMrBWPpCkOBJKaXzWRUsLk4Pxr2mFKi2SOTCpkDHYPKm3aVNzgJ6CXOyhy/+HM=,iv:xvsJdP7SHVRs32DIz/s1d7BB4zeSDAA3WEejQXX1BSY=,tag:x72GdJ4r13ppWA6CUXercg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
