apiVersion: v1
kind: Secret
metadata:
    name: mariadb
    namespace: database
type: Opaque
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:dunOPQe3sEQXC9Mw1I71pltYk8liXvws8H5PBXetxqaW8P7YqN+S9Js9JsI=,iv:NKR68HUNvnK4UuvacMyJNQ91nmY+LiR4gnmwN5w4dgg=,tag:WRRKE5gzQYOHj4tHRytEcA==,type:str]
    wordpress-user: ENC[AES256_GCM,data:mj7x2Y3KZITJ,iv:2KI+wKcgldm3dgGgs972OIgf+QY4WqbnRhuke+rtmeE=,tag:+2piCgj0nHcF2hENrbqL1Q==,type:str]
    wordpress-password: ENC[AES256_GCM,data:wQI2U6HUEb0VBd8O//uE5KC4Usxepdev2skRgWsfDsAVS24dUpDaDFiO54c=,iv:zaVDqwAUlcJy1HhADpPzwgMkMOpPyY8PRqci4RVgtgs=,tag:g10NS87VQWssgf8T3xp+cw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWlJRVW96cS9XVWNsRmJi
            VXRVaHpkTElCVmJYU0g4cDFqOFRiSGM5V21zCk9MQVhOY2IwTDdTYWhodm5uc0tE
            VVdFTWU2NGhYeHg4bkp0aFZRcFNLZHMKLS0tIGFLUVVjaDFHdUhVOTRQczlHWVRD
            bGNDdCtPVFNScy9GSk9LaHFaemQ1bDQKuqffIt0bFChv66c7dEUyZ3sScqU0joqc
            3GXW8nFP+NB3sRSFM3E9m8nmHFDGcqEYeR7BQPyMmmX8MMDnFC6RoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:15:46Z"
    mac: ENC[AES256_GCM,data:DgG8/DsNS5z/SAxRlqj+y+ha//4kiNFMzcVHVx+NTbLBXKscUHDK+FrFKCL5jowCyn6B4RWFHzo/gQpwx8XjcEpiLKejLO/T2lGV0Fy25MnWpfwbiepq4R6FSSYXd2Jvt4CLS0dWIWQsePgSmhjhn5FSdCneiTu4gSxRnOLspZs=,iv:OVx3/1ixkhgvEBypt+Tn+TkwYa+VQZqSE5/Sc9eb+Lk=,tag:VAx89Bun3Gfm0Okj/3joCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
