apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: core
spec:
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: cloudflare-api-token


