apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: privado-vpn-credentials
  namespace: core
spec:
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: privado-vpn-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: privado-vpn-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: privado-vpn-credentials
        property: password

