apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: automation-atlantis
resources:
  - ../../../../_base/automation/atlantis
components:
  - ../../../../_components/resource-profiles/c.medium
  - ../../../../_components/node-selectors/pi
