apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: core
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:nFkdNQwVfgYY7TkMswV5d2O0dSRLbI/qQDvOEFfwLPOG9+bLz7lSmA==,iv:fmwVtm+ysn2lVcOXwC7fTI+2e53fX9zJa3lJcUdj+so=,tag:1mIJqfp2TYMwCxqxLjbjHQ==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:VImqt0+OmhXvKCTxJDc/q47tPdkp+29dS9OzgNaLxxDJQyqb1kGFdw==,iv:qYH3bqPxBBHh+Qdh+cZLXQn3DaVWQZfbzpUbp6yKb+w=,tag:e1WO3rH+fI9Sbi/9kx3TVw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbjBWdGNEdWErY3g2bzNK
            SHZ6T3pvVGNDOHJjQ2RHT21zbUE4d0RqdlZZCkFxSmZJZURFWGx5QzlFeGhhMVRh
            bUFiT0ZoZmpOaGJQenZKb0kvRkJweDQKLS0tIEtFTXlwMTlHTmtkTURqU3FEL1Ew
            WXRwcGd3d08vdzNLT2VwckhOMDd2d2cK0NWkk9WjKv/Gk2vn+tNXbN4MuAXZ02An
            mSVCZgpAJ0EAU5Ja1hG+hhNEZCxkJBVV5/RMj7KH2AuQyqT3E/GvfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T21:46:33Z"
    mac: ENC[AES256_GCM,data:X0SWdFDQkzpzB5TvF0l0cW4zSHhhS72TXq48kUwoCj/ZKHxRRe0lqPfDpB1EhLtqGLSfONNGWRr9qYkWXZ0LY6c3r8vRmY0RD9XnQE2xUh4fCgSMsBnTN2rxvw4XtGqA8w+rrvxD6MKSgscq1rrfWt0jVN9hR7gLHfPaMNiWiRk=,iv:bC/+UOZz4fM+D3FrwV4ZlpAI3kz1w7DpAbh/0EGQS+0=,tag:Qk/K/QL+4kd3W8PexBM6TQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
