apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: core
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:HmLxPhQgXn+Y/vWhJP6P/HxvNwOxfmc3k5+5C1cyAeqPoRjjZwCK0w==,iv:7ZBi4fPEQFpx2pWU+g58sBaeBL9J6pHlG8oJWNHVYDU=,tag:PBettjXSq/koZLfgaywGEg==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:2WcO4BsAInSeLGjqJLtMUraiTZh+ZdByTO2PkpsC07dD8T0+jNvlIQ==,iv:wnPaJrCRyF1fCx1Jywbn9zUzTcfvRlYANE2z9cBJUnU=,tag:KY5AgoqTdp4c5Zd3v8fO+Q==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNVQ4U296aTRDYTdXRXdz
            bWJVSEZwU3BtZjZ6Zk5hUVdWeDdEdTBFRDFJCitOTVoyeTV2VnRON3UwbnQ2NEVM
            UmpYbXplaHN4MVYycG1pYVdWUVZ2elUKLS0tIDBabnVnYU5GTlJlcFlSb3YyeWti
            NnMzRDIxa243Q3AvOUdxQnFqRVgyTTgKKXR4P5qXYFL3s58GxgT/wCN4OKpdL7v3
            AOV7IomKPs/FLBTCf4Mc6FOt2bqQXS7XVERth88HoTecCjHIvUGoYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T12:45:36Z"
    mac: ENC[AES256_GCM,data:sQw/DAvxOL2aa9lqxYKzid5fJTLcEtmLHoCXDUmJo4IPjHCraXWLa9evy7T4hae87DClMKRf0JLSQwqfB/kEF4hrzdChMw3PbBlGcG8Z9zzdV7NAz4XJ/ymslbP60iXR+DYn39jgVxt/HE4v098BlNrtL9Ben4IMSL1eKR6VA8Y=,iv:mL/KUr4DQp9KOtpZwnWgm5/JfBR/OucV73SZNCf1mKw=,tag:9z/gVhWFmXIAeSxeXlintA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
