apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: core
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:NNzaN9oMRoQaYYspwcwcslnTt8lCWr5h+E34vzSlUFyycV+NUh3Aw3UawdCwUpUWi7zyBuOxBRgM4Hs224mx9SXz9n8V36YgJTwyDvnM+DZQjbKO/3Rei5b7whGqoCnOZg2teKVPi8vzwq/1ErWhOCo/O0ADCTGT4clMaeDUsfQZ3JE6JsCsDoVhnnW2yhgckAdjeCQWVrrhGvUWeYhIfT/psqjgmsYiK1Bp2i4Fl7FtVyGaGQ0cMw==,iv:uaEBjvpiBgR5+pNkR1gwYSfan44LxuFY0/G3y+olN+A=,tag:HF7tnS4DunXvCl25dybAXg==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:eS50zFpxvvg7Vebpw2+EYd7naE/uQQ2ba/eMKWcIURdoD2BubLmV+v9s7g2KlGp5cvb+8gN5Ro0=,iv:M/v7lAyq/7TOrGnljCyPAYIPjOWjBB+QZZj2ZnkKOPE=,tag:h2rMikpibFLNHH1wRew3zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaG5WV0hZRyttdXdnQjVI
            Q1NYalBBL0lkSllVL2NONnlHN0FxWE12eG00CnN1am5QT01FdFl6KzN0RmxEcXFO
            YXNYZkEyK1BoaXRRdFd1cjhDem1GVUEKLS0tIFdmWG45eVJETVVkQjRxdDVSZVhY
            SHdaSTRuc2pwbExMbThtMEQvLzJXb1UKqLDjBo09z0bgUVb7KttwM8p9L2x/kP1l
            lPB2S6x0WNgbT9VhLzVlet0WYDYlXimaDypNLFX5RBPhpMipLzYEyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T12:17:19Z"
    mac: ENC[AES256_GCM,data:SGr0qR6pqNAu1NR4m7kosu96LN8sGetXFZkQLPrgAGN27B3o8+VY5KUjBaeU0yg64zZlFdlprj/HLgeIqUihOR/yXhHyD3kMS1PBFkRwdfbvshnkzhiGk6CjzeZrcXYnVkOG4z0HENFinPToiwwJoyCHGqIXyr7WyDwm2en32Yk=,iv:yviik1YbQU5fw9cPV6u3HID0ZI6vGDitIsvCViGerTA=,tag:lfiYJtyIEuxelPKk8zMHew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
