apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: core
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - ../../../_base/core/namespace.yaml
  - ../../../_base/core/minio
  - cert-manager
  - cloudflared
  - 1password-connect
patches:
  # Node selector for all apps
  - patch: |
      - op: add
        path: /metadata/labels/node-selector
        value: pi
    target:
      labelSelector: "app.kubernetes.io/name=cert-manager"

### CERT MANAGER
  # Resource profiles for specific apps
  - patch: |
      - op: add
        path: /metadata/labels/resource-profile
        value: t.small
    target:
      labelSelector: "app.kubernetes.io/name=cert-manager"
