apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: core
resources:
  - namespace.yaml
  - cert-manager
  - cloudflared
  - external-dns-cloudflare
  - external-dns-mikrotik
  - external-dns-mikrotik-2
  - minio
  - vpn-gateway
