apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
  namespace: core
spec:
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: mikrotik-credentials
    creationPolicy: Owner
  data:
    - secretKey: baseurl
      remoteRef:
        key: mikrotik-credentials
        property: baseurl
    - secretKey: username
      remoteRef:
        key: mikrotik-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: mikrotik-credentials
        property: password

