apiVersion: v1
kind: Secret
metadata:
  name: onepassword-credentials
  namespace: core
type: Opaque
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:PLACEHOLDER_FOR_1PASSWORD_CREDENTIALS_JSON_FILE,iv:PLACEHOLDER,tag:PLACEHOLDER,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        PLACEHOLDER_AGE_ENCRYPTED_DATA
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T14:23:00Z"
  mac: ENC[AES256_GCM,data:PLACEHOLDER,iv:PLACEHOLDER,tag:PLACEHOLDER,type:str]
  pgp: []
  encrypted_regex: ^(stringData|data)$
  version: 3.9.2
