apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: core
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ZvJiHWhawxPf1DPvdhgQWUaFDB7WSuP5TgPDexVxWjQgBDw+HBc+GQETrXJXby7/IW5XJSKYTL16gUmkQdrG0qFMkW5CfMSpDrjlOeyW0xEoatWx/Xpht+WYFI60Bqo7gAnKp+RnHO99KnlNwa5mWITJfiaiXagRpZ+3vuGFGMedV2bxejwpBo9SG+WEWg4699YGPwJYWit10/mrvYQodl7Rbs0qxE6FsOFsKxL6Y9Vk8pFSydV77lvZuJk3z4i1HaYeWqId0lQMC30l6n4XmP5mmfX2sFnK89JzB6FcM3tHilrP1xzV8veOgvzc5fYc+63kT3EuxuC9sfVL9vrf09Tz5ANGTlzmkZj+/ZIwa8zShusZCxWDhIVjkU2YHR5OMIwMX9dlmX9LIBLsLmaj6kOmWNmm1F1gZqxkn4ZkHuzkhbpX5cKZSBajnD/HSdZY0s212M0vmoLt6q1DK8KHyiF4NadQ3cTTHDwp2pazs2LBnHG4zmU/0Dt8DiG5mWa3l+gkUslurBI9RhwMUZkPLu2oYnXaCH9sd8FAel99ZCSLKkGazZOI/M2P65sjjFApe4YqXDGmY/FxUIJ2OrbJ0Q2vNtRnWVLiLt3PsYFhrT5gDnj4D1STvBZjiJPmIYQo6m/IzLLfh4XfP7NmUfMWNJN2xba+FNxm1DgfVqRWsXkjNqz4oDJh2+hk4LTZ3gPPmRLQDI2tCCIqcEiwgtFJ7kMscWto6/wylPYu0Lyv79wvRu9n5DQs+encTDXKFzOPw6KYvEBg75eKhJSQoRwP7T04stqB7EzrA5THTTH7YHvw1774kbdwj+WIK6jlQg1ZowrYAKdUMd061I5jRwbG18+u,iv:C4ZpFLmLJVSDEIAIb8zfO9B0VnSL8AjudFNvHzHlCCk=,tag:U130BfLPfU7Tu8qgfiba2A==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVjMreStxYy9oaU1yYkUx
            bHE4Q3BzU2hUM1hxbnZ2ZmZaOENKU1FyMVJNClZrZ3dBVkt3SXdYcEo3aFJTbEVE
            S05vZlBzZWdyVWVRVVFtaUVaMmRpT1EKLS0tIHlHNDR4TngwRU50Y1JTNURuVjdE
            S2FJMlRxTzJweWcrWVZoblVRZTRqeGMKLa3wJ1l/KDIVg9wr68cX3jpu0JRIYdiX
            Ie7wYMggUiHo98NGGFQCV5STtp//feP1f48ly8sFczg1GRAaDCS0yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:44:43Z"
    mac: ENC[AES256_GCM,data:OA2pdSxZN5qHvFAn9IzKbvXIn9mnZyWbmedoxL6C6Shy1KbM7cQp2uJSMsJCnhyVJB8Y0FezCJO7Xcj8KfLeRbMZbbzebP0MF32VGWNs4RoTKm0sA6oWKH+yZR+hLHBZeNYz3GQ6eK4z1Ewcfw2qCjyJyA4HY7BUV90W7Yjr0wQ=,iv:rSuGHjtqOzP0nvQe3BcMgqZTQSWizk+ZTuhZ6S3axnM=,tag:Tgy0iGFc80cxwR9dZTwy4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
