apiVersion: v1
kind: Secret
metadata:
    name: onepassword-credentials
    namespace: core
type: Opaque
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:WYhVCinvDkMALgD9+mBfczBDajZ21ytvcpVxUHzCmkJV2eiK+mzx5HOtdwku+TyGK770up1Ic5tS50vTqfTEWWaRa+dlMyj0G09xs7g7AFFL46hsn0zA0UDkb/NH47J9kfxzTOxjkZti8KvAc8/XSOWxNFTyBFsziV9YJbsPL93I7FeucIJRZOXXQycKQGBQ9GBJ+PuaswF6W1cnbM8bDXyd8FZx3npM5QuOlT5t631+D0WHgJmmqHMX09zYQI+HhadV9BHHYtutkHSXzpXur1yyf1eSe9V0N3cmaxNJDmpdXGwncVGtsgppBTu1krUeHoHqSf+YQ5cFjjl0BvcXmklWjZEp4tNrI7Z7kYEsog09Zhm18AeaTZ/GrnLm+a2vdwjAiAgIKh2conlBPv6+ZyoPzYN/qgJL/c60lhxZ/jQT+Xw++1Hp0VyAboBRPgQMol3qASuwnk4i+fdo36VmtDrHwEjTpY7a6huFAfcvtyWixWn/HS+30fi5zJX3z+OWGU/cYDnyzZwnxYD1DWKK2U8HJ2EYf8Ol8UiWmFmQHkZz4R0x9QpS3uRyYOzOMhv22l0/LxIrQmQAQjA+k53Ur9taviEsLqOa1th8m7HgDAEJiIANVX7E96VRqqgF7cHL4HOOOPX87YQxo8D35XCN7L4PRTU0sV08XLm1/q8dtWngIlmZDKPaec02CQaKsOOAPQhSDWEDa5o7UhLenSzFxHjkToLTUQMEqf00v3Duul8ftWWRETs4x2HvsPcdgGxO4XLqZP6u1CXfymHcGLejvMplUp27ayTUj0MSbFnGfnenDy7cL50Tewm52msR3+EWlNo9nwbDJgxTMR6XU1nON4md763aMUv7RsDcazf2ZB/Sr2dnq/QB6wdpNtH0RlGTCTj+5Gj+Y6hPtdA5uzPD+CgWKjSPEI9VyU2Mg4p7owoAh4iOZq5vsYXUtfLmPNRq93XNtNTUzLD3g8jTG4LfckppE7Dn0Qc5MHQjrCfetwo9nh93/OCcjzz6gw4QODyN+BBSKN72bCeYK5/gLze1lkk1ZQz2Cfjp8z5VHoOCdWZ+eCpfRffN7EcqowY6AYFcP+PCaZtVbaviXKLJQfr/LPLge6hyRUGOaPzshjzJjzTjfJvskQ28dh/aIfGKFyTBUs6E9yBQ+UPcJz6JHcKUTn2WnKg1tFZfHuQkGNqUl1D7npvql0bczeS5Thro0Ei+cMvXtMOcFZpdOlhQ160wO2plvNYfkdxFxWANAvjptplOn01d7h9nEIUcfiCLptVsznM1h87Wi8n1LdRqrNM0txiTRuqh6kIxHt40BrjUpbhldbqfjO9kXpQilLL9gPjkrnJKG7v4WpxeNXG9sjqlU1TnEuU/St72Q9a1hrBsjaAIO2WRFfdIwjGNy5r3NuEZO65mKJ6snMdxggHm95hftQNqMDO/tV4Qx0RqzoRWCRE=,iv:uPex4SD8tin8e7Ww4vBlV4fa1//maMlyvXYO9AqONes=,tag:6sEVroDkOVB4MOp8+ZfVkg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeWxzdVVXS29MWXRjOVZk
            ZWFvZ2p4OVVtQWlwamdiV0dlSHNVZUZxM0RvClUrTEFzWWRrSE5kLzZQdHFQR2hK
            eElJelNtNkRGbmZKeGhsZzg0WjQrRDgKLS0tIFZ0SFozeWhQeUM0aDZ3TDUrTVB6
            cXV3dkc5ZTlIMFc3YmNtRFk5azVWaUUKKLE2IAO8tUUJV3iCX0H+lcQHHW0jN0Z4
            Jh3IHqr52ULVBMkt3SGCwhwH9vQAKrU9FTN9YvEcI5ZeBb07Z5goAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:43:47Z"
    mac: ENC[AES256_GCM,data:hDj/g6dRv0d084XcZCnkZHfqeK9tI6bodfbS6I/RIKGEEDTvLZeYMWuIJ1VksP+RCdk+MPS1/7hI8B/oV/mANHgXWx0TYGpNQ6qOQQ5lKS8tK+ckVXs3iDrWUFckWyTxf41cD4lKPBL4U3ay+rJGQazpV89M6Vh6tFfqmU0XBog=,iv:fW3yPbTWFwTp7VqMrCcLzoFavbWv4aIOr0U+YGelPyk=,tag:kt7B47FTIrEH5nOT8R7rJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
