---
apiVersion: v1
kind: Namespace
metadata:
  name: misc
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    goldilocks.fairwinds.com/enabled: "true"
