apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: core
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:D5DjZzRJMdnZ+vLgaiu6i/xV9oQ=,iv:hH9cXbosGFyGVdHuWgnhb7VGsOpOR6J09Vi345uq+iA=,tag:aUXCsDXaIxvXH95QuOZNlQ==,type:str]
    thanos-password: ENC[AES256_GCM,data:pPDsf0XDouRxOA5J+AR+bqbtDqs=,iv:dDb08syLDsbHH/b/p2lGnUxMNR8M4rlca9bVcQeS++E=,tag:NukqiI4dLr8FDkMUNF+05g==,type:str]
    loki-password: ENC[AES256_GCM,data:nWlKGT/IyUYKhW00aCUa/cP/ZIo=,iv:ePjQ5VGliIugIkZoojE0plBN8z6oXgVK06Pz47M5Ujw=,tag:4ESbwsNJ9ouM8YM6Cux6+g==,type:str]
    postgres-password: ENC[AES256_GCM,data:Whl2WBDWMT21wTNst4PICXFmwjyFoCo0,iv:JlobeqvdEQIuCv698UJs9tW0Dp8G2doGHBMmIr6yqJs=,tag:GB3yvKJ08tZaWOoyuI5GxA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaGgxS3lsa09HSGUrcm16
            L3V1cDNuYmZjYmJTVEdVMDM1Q0hHNHF0UWhFCjgxL3pPQkJ6dHZEbnhyMExvQlVV
            dmo0ZVRia2V0amhPdU1YNHo3b1Z2eWMKLS0tIEthSUtYNXRQVmxJWWl3QmsyMW1w
            eVpCaXUyMXBNdjk5NTFCdTQvMmE2VUUKLZ4PZdDc4pNBBrv/GL/4R4ycqMglhBCb
            dokRtV1lT4bMc2pfQ4a9dMNH4+LqudSXvCRpB7/6KKUTjrJfslcwGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:33:33Z"
    mac: ENC[AES256_GCM,data:io/RcVVt+G++SJD5Bj8Doe9+jhumySpHUBjVs2Q5yxyLo3/Zx1QsudRDHNq+IaU42wAmZFR6afWQsnh5Gwu1s6BB5OgLIts/6RdYF7OMV/nqaZ270A7SyHdq7nrGiicdDrE5PfdLDguJPNShrlNVfyDYnE6X3WhUyGUr3GPkGEE=,iv:0T7mZU+aRcnsWcQVewth1t8LBFeTQ7jjI/L2yvUR9F8=,tag:YMqB1CHLoVtTqovZ1hFXgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
