apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: core
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:bxeeKseloGeRLCDi8WvyczCO4ts=,iv:XBB0Y/LBaqfLHGq+Q/odgkqOj4/FZQWeTtPT1szIyus=,tag:5zNkovlkzik7kDxTYW5QRA==,type:str]
    thanos-password: ENC[AES256_GCM,data:MtVDBYHDtcVKWzMoWjx1Kc+ELQ4=,iv:9vtjVaa/rDhFlbd3m2EpX/JfSFyAFzwAam7jajA8rBg=,tag:r3Nt2gY+NxaIKMaJNpw/SA==,type:str]
    loki-password: ENC[AES256_GCM,data:lymczcOHVZ7tni276d0NkutrIq0=,iv:XIovVIFErgTE+rGcF8Kc1CB95eibQz1o8GPPyNViXF0=,tag:rASc1xmVc3VjqbMybbcDTA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUTAvdUVOMkRyS3F1aFY5
            cVc2MDdNSHlmN3BsRHh1WmRlVklnVVRpZGxZCkFNNmRvR29RRVk2aFNsektrWUkx
            YmJtODFSMVNEWENoK0dsUzJJUGYzNmcKLS0tIDVGWTROeEFGcFp1eTZOWGlnRGRk
            ZVR3M1lqUUNOMVhMMWJQWjUvUk5TNHMKcMW4pZn10h1svFRVTmiXQlLeht1wuHnh
            PEZETwDeTDpZiZlnZMAnojKLxZ+RvXV/Lfq2SgMgbBNZkzJx8syZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:42:15Z"
    mac: ENC[AES256_GCM,data:zJHRqG6VsQBXIeIWZRmLof9f+moS7OjKAwMrONdPxvzOYlRxVqe0V4HFCcy8smgPBoFwgYY8Q7eLsqzr8yjDPP1IVcx8KZ5CJ2DG387DC3EK1bet8K2WpMc7XW2eO+7Vatn9Ft7IRRHWrxLv9pPuu7DzozugyvDQeFoE/X2JUjg=,iv:kxwMwydePDelbJAA+ylxtcKVr77QnrF3OOqENpSIsHs=,tag:N9vOqEFMaDZx7VW7FyAvqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
