apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-config
    namespace: observability
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:Q5eHyOOUnCvjOxUNaa+VEqnBrZfW0XHM2QyaY4A6I97DoxvNsevsPAgK8DMu4WGdgO6i/d1xX/1q8Ib1OxgSMJkxmRqL1jY9ER+/6fW6slsZif6yhV50Nr5Y3Z1RMbTbDAndikEuogblwIHfSynlSyj5CeecttPE4WF1Znl8iXVdiX/42ZMFqmjtqgo66vQEMAnVHYnb6NEPpO3ajYaptY8/mbkR/jojXCLd8dy6YIqubiTgUQHeo24uXRPKoIWDeAqPwq6Uj7CMhiKn5bYP0udcKETY1tO2uWapiSA19g==,iv:TL/tZ9pK08hq9CqilnRkkG+jAtc169LosU41EFVcTGQ=,tag:XN+mcU8mKZGUBn64uG5gvw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d25XRnc4d3V3Nmt6WFQ5
            NHN5WGJJcm1nOUVlbVYwQ1hPQlpQZmUrWHpzCjY1Nk16eGlKanhVcjFsTnZhV1dk
            UXFiOHl2RXAvNDlOUTM0OE1lbzMyb1kKLS0tIElkOVJteEw1M3FDNDdXeWRReFRW
            bmF3aW15VnJpTGJWOVlBbDBtdldjWm8KeT/58MXG6KRCJJRb6fQp8s2P1VnWTjAS
            T2TYiYka5irt7pEMS3qDwtx6thSCIaRqb4E1ZwaXRSBKsGoAk4g90A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:47:26Z"
    mac: ENC[AES256_GCM,data:UdUgb5Vg0vdDMbAO7hhlrjUrk0aAapOGl7W5WEoWCr+8Qa/bZ0+waZ5UH2lVzFCx70+6O+5X79WcEK2mklzpU3t1hWLcDrgnDTdfeChoFupTF//D5xPW9iRbuc0OQRjiH6xh84r/v5RKj0kTwl5PsQKZB3rXD/h00XeHdCcwg7g=,iv:h9HXy7N6ePuLoF88zk33AFVrY07gUB8W+gVjypDPPjw=,tag:4LU/oMPy4R1Fwlq3YwvRKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
