apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FMuibWRfqOtTwCY53XY1uZ53UIkjzmZIvUGQ1jbbmisv/B6IjJKd/Y0XxUR8i/nu3TJTaNH25KnQUHD8bvcV7JvtIkDyc92ia0v1kTyBnLJchMhkwcuiWkggNxj4bW0SSMW425L3ZfSfgcekh31wDo6+7tn/aJylr4qdsNo17QHNbAe2S9ZJW5/mvpV2ulcuGqz/89VgWY/oxXJduhBMjKaQtQ/536hRAjzstuEjWpKuaUkZMwLxnQVeqq6oXkDl9HeP/3Mxv+qRueL3xZm44PKovrf58dx7SscMlIvPBwZKq8y6vWLyFE/XKLqFRCUTFcQZolVa1w0=,iv:+ODsKGtYH7oi925h7Lycr+3bvF9PCVAgWgmiA77G/PI=,tag:S20svP38jliN4Szp38SRTw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: automation
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQTlPcytXNG1hTGZDMEZo
            S2FJb05hQy9HdmN0eFhmaDZyTDVPdVpHOUNvCjdEdG55ZWtSaU1McXJ4YnVJd1ox
            THpqd0FWSlQzWTkxdFppbXFnTkVTRFUKLS0tIEhIQXp4NEwyZ2hqT0tPWkFXdHhu
            Y0VmQk80b0prbGx6UmRNS2Z5WmVrWlUK0H2ZLBYdryK4m2IGxTjXU9gvEEZaPeEz
            u/OxOHvdCoF/PQRLkgXz1s1/KhRWQXrRMsLq6yK+N2l3T4h8vGTxKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:48:03Z"
    mac: ENC[AES256_GCM,data:aRnN7ZjoLc7xjS6mzS4MuNA1UFdMsesx1S21wgBPn0EiFINW9n9QoA8icSzkqkRNvAxgwqrXATSx9FX7H6V9N4DGE7wOw/togNpBQZJmCkME8TJf3D9vqK1lU92qVrZPWNfjxWDPK2Srxqch2lTpDwYD9YsVRIl4xz+c/L1qKhs=,iv:FnNegUakiYpfJe8MxbCwznRIxTZ6t1BjA4tBrMOk1yw=,tag:ZlmxdLWY7n8cAwMrpYgkXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
