apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: automation
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - ../../../_base/automation/namespace.yaml
  - ghcr-pull-secret.yaml
  - homeassistant
  - homebridge
  - n8n
