apiVersion: v1
kind: PersistentVolume
metadata:
  name: timemachine-share
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: timemachine
  hostPath:
    path: /mnt/raid/timemachine
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: timemachine-users
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: timemachine
  hostPath:
    path: /mnt/nvme/timemachine
