apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-share
  namespace: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Ti
  storageClassName: timemachine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-users
  namespace: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: timemachine