apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - statefulset.yaml
  - service.yaml
  - mariadb-service.yaml
  - ingress.yaml
  - pvc.yaml
  - pv.yaml
  - namespace.yaml
  - configmap.yaml
  - secret.enc.yaml
