---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wordpress-data
  hostPath:
    path: /mnt/nvme/wordpress
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wordpress-db
  hostPath:
    path: /mnt/nvme/wordpress-db
