apiVersion: ENC[AES256_GCM,data:z+I=,iv:fe5jj27uWP9bGzQ4uuykAFSlUlEXWOHj2w8KhxGBJ3Q=,tag:ESLG78Fu/59gnehi35MpJA==,type:str]
kind: ENC[AES256_GCM,data:qx/C0Nu2,iv:HLoz7+hwf+t4/RUex3aktSCrUiV7Dgc1ZnwOlcRji0w=,tag:Xwj/fNDssPPmTebCifq5kA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vfaoxypZLXBrbOk1,iv:XsYNw2xfP/abVp/+lkd+fGV0enjarwWhUBWeue54L/8=,tag:YBJ1rBea82lSqEpzcEd3Rg==,type:str]
    namespace: ENC[AES256_GCM,data:wfKRobsm2O61,iv:76F+pYpIQnjOFm81KkITw/2a8tCfsBDIDeNKazGHAY8=,tag:Gi5WLfXpZRcZBsvAzmB7Wg==,type:str]
type: ENC[AES256_GCM,data:56gDiIyt,iv:pW/nABiK6ZdDxVMXMqcL8DaQ9jqJQLDD0k1CojgFkYs=,tag:iWioMoJuwoAu8y+AwVVpzw==,type:str]
stringData:
    db-user: ENC[AES256_GCM,data:ueuywapB595R,iv:Tv1xuQgvnzdVSjKus9lAKqjQYVdQr1pkF/YJ3EBn9+Y=,tag:UyBl9FGC8iPzv4qPzzFdOw==,type:str]
    db-password: ENC[AES256_GCM,data:JimXWgxFj3QgqUpismNpSxuxW2NVg0pv1TvayQYga2zaQE4keExIaVMjIH4=,iv:ufjJ6Qox/0XflIl1kY9EnwCO3TXpIdaMjBj4MqV82V4=,tag:tutTVtY+UkKk2v/+vAEJpg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMWV4ZGk5Z25rc2RiV0xh
            dnp5SHRCcm9SUVRqa2lacXk5cVJpSFcvYnc0CmVlL0dCTjdWSlYxNkx3R0YyemYz
            MUkySTNtRDh6MFhSR1JvL0FmMnNEWTgKLS0tICsxZGlWVm1VbW1uQndBdS9tY0Fa
            YXBHeVNDckNkdVdlVXE1ME11cnhOSmsKoOL3UndnYNyZt16k3SqU0fxI9YCye2Fj
            YqwZNelP2qLUgTstaJDAOw1ut7c1wFqtAQzs9WZDdaAMA6Wu2Bsvqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:13:57Z"
    mac: ENC[AES256_GCM,data:zMH4rsEz0k1knZJCGCX4xX/Ysws7jMyu6YXpeASMjsyYAWYGVwNM7cZOv75VY0r1ME54NtKmOo7o2Z6hbrhNtHi5u/a/ICTPripooczbn25Qh7tVcJiny9vwG8DxibS221ZD+D6EsJXI91nKCwXJJL+cxxSb95dH5Ot5Q09LAeI=,iv:BaIpsIK27G6InuNaOIaHN24OKIUxXTd1ICKpGolNNso=,tag:4e55+7vJ+4t/s5CVC2DHxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
