apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:du/qCDOl7b8m,iv:CT6BBznSdcMvprj0/722PMBacR8leG5k3A20N5iKpzA=,tag:3Oz307QoU5m3PFxVzbirow==,type:str]
    db-password: ENC[AES256_GCM,data:gCfLGJq0wfpDIfL7p4MPeERmp0+7RRLaMysSjX7nzN6Qk3bQmmibk1leND8=,iv:YXij+Llbvpo6lV35+yM7IeNO796n9vyncgn7XT1RBGw=,tag:UGFAQaSA/24wS8WjzGyQXw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQlU5K21ZakF1NFVoN1lZ
            T1NlZUoyOEJGVEZicVZNMzI2aGN2azQ1dEQ0CkxuallpLy9BQmJrZFNxTGxrdFpM
            c3AvNzJrdVl3NmlNc210RHZxV1dmbXMKLS0tIHVpRVpNODZzMXhsc3BzTVZuY1hJ
            UWxCSVFOWjdpYmZjdEFUckoraVc4bDAKl2DdQUtg6Dr0Df60HAZwZCsRGM5JDSbu
            aJSVKtHm64FsEquGyfezzi6y/A00o9VkCJaAbspdHLT0q6vxZ0FLSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:15:47Z"
    mac: ENC[AES256_GCM,data:nFi56oZmDOYvtVFpNM/dzVjjQa8pqeSZF+DEYUMWKvYjHLAxYfh738A34JmLHQN/EPfIC2qY9c1A2AgBJkcDGo0JgU96SdBEtDhbrFXFd9/cJj6XeJTsmT33jkvsRTzCrS9Fu2/9kAQXh5PBRNk7c0Kdx8bD2HiQTGheVgmxPEw=,iv:iSOPbvdXLT5MFL7xMDpVMLtl7uxu2SCS6XFJ+etfAQo=,tag:z3MkiEu2g4DWLLDyr/4ifA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
