apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db
  namespace: wordpress
type: Opaque
stringData:
  db-user: "wordpress"
  db-password: "CHANGEME_ENCRYPT_WITH_SOPS"
  db-root-password: "CHANGEME_ROOT_ENCRYPT_WITH_SOPS"
