apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      automountServiceAccountToken: false
      containers:
        # Excalidraw with persistence (frontend + backend integrated)
        - name: excalidraw
          image: ghcr.io/ozencb/excalidraw-persist:0.18.0-persist.1
          ports:
            - containerPort: 80
              name: http
            - containerPort: 4000
              name: api
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: excalidraw
                  key: STORAGE_URI
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "100Mi"
              ephemeral-storage: "1Gi"
