apiVersion: v1
kind: Secret
metadata:
    name: excalidraw
    namespace: misc
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:GyFzt1LZwTvDaSyp2gWJUFDM8H8=,iv:IkOq2CtaX4VYyY43j/y7+U122XgNYvWzSiw7SLUpMng=,tag:Ig1BF+mFe3bSiBFiz4M/Ag==,type:str]
    STORAGE_URI: ENC[AES256_GCM,data:XypDbLOJjsxI924ZaPndCjnqyboVuPNWn6qPVjUP6k8MgcyUuaAc/lHOVW5lhpaCNTZ5Pj31+pjZiMeGscYXzh0kd/DmWSuCGsmjdlknHrDkXP1rP7igPjHvYCT085n9roI0,iv:2yehXzMG1iCOY1X6EqXJAcuqrjCwg48w6i4RePTwUMA=,tag:X1BKqlXGqedae5nUby/7iA==,type:str]
    #ENC[AES256_GCM,data:se+bFvqqUt4Myeurzow=,iv:iMFIn43KXs/5K4XoDKFyUq8ccznZtg3ofr6guqLvtDc=,tag:01YDXfvwP0c9cShwvPPXFw==,type:comment]
    #ENC[AES256_GCM,data:Cqc1iMTAwaCtmNtk,iv:4l/kGG1iHzTK83U+BACEF8QdXNwve6u+bhWNZwWcgUc=,tag:3lGkn/SOfDMG+LZ026vhjw==,type:comment]
    #ENC[AES256_GCM,data:u9+VqtaR23P6,iv:4DV0BZH17yp05NiVD3CPxg0Mt6ILVg5bE15ApS+35C4=,tag:t3Gg4d2ftr3cmajvY+RK4w==,type:comment]
    #ENC[AES256_GCM,data:o1aELbLVel48A9YshPGZdrVv3S5zdSQUQYI=,iv:ARDd3+2VxBjUotAUSEtih7P0G6caSJfCWVx+8rEbj/M=,tag:Yoi+XeXB+QvEUX9Oj2r28g==,type:comment]
    #ENC[AES256_GCM,data:qwBBumoY6BhQmD6IxC7MNlE=,iv:Lx4uGUVbnPQUkenYlKGJVOmiyA0OqgSxC69UTBqypa0=,tag:pij3Du76TYMiXQNTfb1AYQ==,type:comment]
    #ENC[AES256_GCM,data:O2bjB4ZSMGzU4VNV,iv:x//QWNXz7b0aQqqbci68q6dn8Fhg+WyyGTH2pRSIn4Y=,tag:ynjgUTFs0aWke63XEgXQmg==,type:comment]
    #ENC[AES256_GCM,data:x01+mpIfmVXFC5E=,iv:j5/j+Ny6qdgREQkaUXKcZdPNMHTMrZuG0Yys0fLmrUc=,tag:q+1Wbxz21MqLnqFeguOHaA==,type:comment]
    #ENC[AES256_GCM,data:kvo7mO+ejyEbxaHv7o1/8wTunb0ARq5u8qCH9u5JCEzVm7te/Sg+Y0P3UvuQjSAwxX4tEUQdTqA57w==,iv:YAONRddPbr3BTcT849qU6RGLfKY6zOU0/Fu7tuAE/74=,tag:S7VOzo0mdgzyK3HLOHLrbQ==,type:comment]
    #ENC[AES256_GCM,data:rJN5F8Yse/QoeDOqX1Lc7EADTLOf7ciZIKSAbnzkB7aCxCW6L5f4aa8HkKZ8bz4ykMh+0Wmyov0+UovodU2k+FDYrreKNE0BlKJPd8ZGTjHFsx/+BZAFvZ8rhOTPNCeQ4j2D/VUmwYZdFMmN,iv:9XLVirF2q7rUDK5Tqc/RvFyuC6EyXxE0DABkMTre1yw=,tag:El4FEsWNDDsJZLPm5gc9qQ==,type:comment]
    #ENC[AES256_GCM,data:CYvg9a/FWjZRMy/9mc6+OcZB8VA6qKGCVqs1mpINI01k3teyeNGKz/DwGVVYq+temOeXc/Cvzo6FfzrvVX+qsyjk2uluWdtpAvph459yrtwoaH94MZXXCfmBvIYA5u54AgOVGLx3mFmzdwCIqDIdcw==,iv:0JA6JM1bELWv87Yji7q5c+FYER7NMC+YyOBjKOe9GGo=,tag:L3RfMxeTuxqURa4a1O4Gvg==,type:comment]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWY2QkgreEZwZVk0TFNp
            aDJWTFptZGM2ZDl4WjYyVStaeDBRZzl3VjBRClFKRXdERE1FanVPTWZTajcwOU5a
            VXV1Q1ZVMmlaY3JibG40T3V0Zjl2d1UKLS0tIFFvaGUzckZRYlQrWTdOSTFMVGFl
            Z0EyNFlnMUpFZmZlZU1PcWNuMGI5cG8K1Wyul+hg+MQFuqb/PM9EKSRJyT2xLhtu
            nRz34EA3xNc7RZyjBcPCNx8In7UFijw5nK/6q7MCG6cEU2XU4K6xWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T20:27:01Z"
    mac: ENC[AES256_GCM,data:5+VXpJMaKYmdhjFAzONF2YH2iBXgXI7t3jeclQ5jnbmfF332qB/w9BsgK2FxKH+omiP/l4pxqhBGY5ToKnrSMAjHRaFYQsKhRKEeu4E63MEIYPdkykaD5dovjRrHoz3HeMi9UKmOltn07PmslABEe1lFmHXSi29MnI/RZvtoIiY=,iv:mh3BENddDfkP3oFF5Vxo7WoBy18O6SwXnURSKD3uz4Y=,tag:KmF8p5pgOqlN0heMoCD66Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
