apiVersion: v1
kind: Secret
metadata:
    name: excalidraw
    namespace: misc
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:dBtxin/hAZ+NmugyEU+UoUj4Kdo=,iv:2FaQipq8J8V1ONFvWX6X/jBIBm4WuNZX+X4l5X/YJlM=,tag:bRKO7G7qb27p5v5Ttpfx/w==,type:str]
    STORAGE_URI: ENC[AES256_GCM,data:ppW4dhaDNvYxnqfsEPxA17ollkdRVIQcr5tdmMYJSdT7XxAgzBJ47bljE0Tj5CqcvwUpYG0Y54An1HgtghcbXxMlPlxYL+NU8H8Ch0O4Zoc81bBmmO3KMNVOVnZd19zAmxCExEu5uFclEN3vPzLI8Wqu7vdfqpKAq5pY8WonGrnNRg9vNjZnXdznJVMOmwY=,iv:83df0pLXXR/DKvW7ZPZtq/veMFfuzS0BRSOmM312OPw=,tag:+KNbbyQr0UHOBSdVzCNcfQ==,type:str]
    #ENC[AES256_GCM,data:NvX4fX2H6P8GNR0Nksk=,iv:4CL9AmyphxRGms1Rc43GztLxAPxXWZjB+xvYYeJvN60=,tag:5pSBGG41mtmE+FqmS85AIw==,type:comment]
    #ENC[AES256_GCM,data:IXB4qann3U0n3LVK,iv:67kyWfCmLrccl/nPtkyrAHTKu67YEgK75XXGgjSrOE0=,tag:lh2HPLBjPhfI9G3TEVcFxQ==,type:comment]
    #ENC[AES256_GCM,data:TWEDXEJSw5OG,iv:Pbn2BPwBD2sKyLvQMGQassN1gSpVOKed0sgvAKMOiyQ=,tag:WvB0Oz1NNdtFB3Tol+1rWg==,type:comment]
    #ENC[AES256_GCM,data:bGh9BWV26YJQRei5HfnC+rhldbNkUlI8eDg=,iv:SDJlmC+FgJED1QFU6pD3HEoJ9ejt4RoU8lohsqkirCU=,tag:/RHXameD0PHICZ507j7JMA==,type:comment]
    #ENC[AES256_GCM,data:ZEotoOM/lTQB/yDy8Ngwq0Q=,iv:IAEtYdraRUCDkG05KwHHTO5blS15/4yYyk8R3UPKV8Y=,tag:G056IK0LbvJCKeMOEfrgPQ==,type:comment]
    #ENC[AES256_GCM,data:6eDRhOj79+ZquqKZ,iv:oQhY1TV/iLVFXcmWjf6t4oAZ3eVbcNYr8RazOpp6Ywc=,tag:rlN7MGnPyyxMZl4AnERiGQ==,type:comment]
    #ENC[AES256_GCM,data:SjRXQiPT5zAY/oY=,iv:j+emNcx7t+ZEHROIgXJx+ol6He6GlxDQvytQ2PohIUg=,tag:iPzKHkZVqeOdBLEiKdTSJg==,type:comment]
    #ENC[AES256_GCM,data:WMAMqeMx+i4DrnKOeE2B07wypyGCJmn8p+hwHjol1iv7Vzgc6ST8n6h6euGJ4zVQbYImKw/UMSv93w==,iv:fcA4R35MkRIRLWS2hzKhTje04GsvmqzhMgKpAOuqgA8=,tag:ambV8mKMizZNTdzVEze1hQ==,type:comment]
    #ENC[AES256_GCM,data:0P+4xjGEoYiMknz/b2+9tTI1hrNLj3kUuJEcrIJuN+8c2VJMHo9dfZgkgd+39nuyS2itBqViEueT1shhjlB0FZHwLEqsC6Cap4rCXeGLue2URciwTOHKt6wO8JXeTPlwlmjnrIM2JGUoZFIc,iv:S2SDnbPsGPfBxkFUK5Wek7yCEnt+4sq3FMZb7WJk/Vs=,tag:8qjgqOL6TQeX1kDlAWxLMg==,type:comment]
    #ENC[AES256_GCM,data:NnTxycMrc+xItd1a5DJc4oeYuBbSbPmp37P3VOENWaS7A6Eo9+sbLZV4Qs4JRjFrGQuamZ9b6TVnm4WwGV5/VXJnlzZu3dsPYWKLZO2jKAIPBit4UAUyIFrMfkkwjxUbEqa25BwUoIpEATI72A7WuA==,iv:/yuDbOr8P5ziBifOOmiZGyNB6s0/LfMk2NY96OK4RT0=,tag:CQCk/8h099WfDBpT/gaBAw==,type:comment]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NFJtczZNMmtib0g0U2o1
            dUd6MTYxS0ZjUzZLYUVzRWdjTlpZK0VEcERjCk9xVkZDeU41VThveTNCYUVEOUJt
            OFgxRjhwVWZqZ0srK3huK3AralFmR1EKLS0tIFA3RXVVZ084S01HamUrVU5LWnM1
            d28yc29GbVowK3czMVNkb1VzOVpTNDgKhkuYxKNh3zkegyKz1CMXZkM0sMTG1hG2
            0SxvYMjc0hcrOSLR+L327iyzH8On772cJF8HBbdN0d8/JwOKv099RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:33:48Z"
    mac: ENC[AES256_GCM,data:PB4aa8vhV8gcQp3jbo95f1apPQYLPzenKO2vu2BHCdhbFXWMXYK4xsRs1WC9grZvEc/+arf4p2F+P8yyxYbqjxja9xD2NvlUPclr2pBLZtEYyw/ZyW6lu1Da/xnlgXkVtKSygqn/mRGCMeNkwW/BaNzV3CMa+OZ3sh78z1+1I7s=,iv:O8UWs2jn0dbkMLc3x0HbZ44f48ewEoVjocAj6KZKyZM=,tag:LGaqd/5NZm0lFLl2qglgvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
