apiVersion: v1
kind: Secret
metadata:
    name: excalidraw
    namespace: misc
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:gFd5iZLEYkitktY064UWMGQnmsY=,iv:insRnChYzF/4Icr9qv1MZQSwHRNGjE9xyloEDeT5waE=,tag:QM7My/NkjgrZg4awsDY1VA==,type:str]
    STORAGE_URI: ENC[AES256_GCM,data:HVBs5043LVw4vL+BfepPhpC4Q3Hg8zaYsPAXefakinyNpGP3jKKZbGDIw4Vc4vpKQdVWdLpLSYGplVBNGCtiHcBic6c973I7mzCrb7dc+rz8sMcNVWzezwM/KNXbZM7A,iv:sW/XP53s9isLy2pCvFgZli6KbAUTUyd7S7CwD7EfxW8=,tag:ORrum0A0Tq0MMd+7xWPtAA==,type:str]
    #ENC[AES256_GCM,data:EzOvBngOuN/i0fbMBig=,iv:aUo2mFuTcwhKouPX5uKrAUnO8IjHYjDj7mQRnX+e06s=,tag:VobCuHvdffoVvtSx89QdOA==,type:comment]
    #ENC[AES256_GCM,data:rTiRjyWMBjRSkuEH,iv:/UZBd1EBx9T1Mj2AIGNzr9C34/7hmNqpj8Ym4WRWPRA=,tag:Qf3pHSoHl2i4NbC6Sula1A==,type:comment]
    #ENC[AES256_GCM,data:mcwicaQIqn7L,iv:K0wu07dVMSEU1XbPeR6GszgLZViXRYP3hLDq4RsNuPw=,tag:j+ew4fB3M7ANPt2d/mtIow==,type:comment]
    #ENC[AES256_GCM,data:QQ/coWlKI9bFevU2YZJogvEFoF9Q+5Dla0Q=,iv:apvimbQEiqcDNHhqCDU3V5l6FoZLAiGCkMyF5QFE4ic=,tag:nZ13UAH9Pz/zE5lb5rhyKQ==,type:comment]
    #ENC[AES256_GCM,data:yQdWSFvL+troJNYcv4BpbO8=,iv:czV5bK0O6kC/6twwlqXkzKQOdTf6n8wT2vU384F0Bd8=,tag:8kkmZoHLUp6+EVytVCoT3A==,type:comment]
    #ENC[AES256_GCM,data:pdQE0VEOh7bkfGz/,iv:pRtrOkgbLV6kCFhs9bI+vMm1B3k4+/SdxBU/KpvrwMw=,tag:yyACrNlJZEGMMfTqI41agw==,type:comment]
    #ENC[AES256_GCM,data:qV8Fpr7Ri7khvXk=,iv:L4U2EYwlQHRjETxSbRUG1UaL/OIdZ5HKIfyEuONsz9k=,tag:UABYkKgNzFgQ51BMsLwKXw==,type:comment]
    #ENC[AES256_GCM,data:tOqIh3LCyDnIn/2ZC4bRKoKr3sTp8Bdeuhie4NUBSe7cYUx8SHD4SkmIB5c4PrmfacP3Kn4l3DE4pA==,iv:3CGKr/fpWW0Xw4hdTj5sG7O+NPzHNTVzpZU3QlPjaeY=,tag:lQBV7zyXBMo6BEEQ7p5zPg==,type:comment]
    #ENC[AES256_GCM,data:tsyAKVn/C2yH6fr7OAf2rRKBGrKj7JFj2IgMbTJWyBSMtfsOUc6nibBdMNbYTsLXqAlaO5YqsFnaAAXpXYoX7j+HKxGtRtXffoEwo3IGU78bjaJLed134Ke8MU72Yy5mzB1oAwgU+Zm1S2Z+,iv:vkryK+1H3+PPNs3156TTEbJJj0xjSs+GSnhwEYhyYE8=,tag:oS+LQl6UtRNvue78UZQCVg==,type:comment]
    #ENC[AES256_GCM,data:6ehd+QWcHbdWbQ4nyKzA458twi6ADCgph2hP+IAwXhcH0vHa1O2F/oLHyFyTja+m2K22ECHFq9NsPjGhV5LtjkyiLvseLHir+I+jSMlWG4NJi0I9o126Fr5cPa39Dsc8il2DM+rqs0IYmj/i8FwR6Q==,iv:kvTdXn5ygV3+ttx7oaa5Xw+Em48SsIb7LguObbf3jmc=,tag:vIzyfco2GPwkreuYD1lUnw==,type:comment]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTG1RQitIMnJFc1g1NlAz
            cmFtaS9RMnd2U3RqdU5uWDdsTTdyME5PMWc0CmQzT1FkNVVGbWIyeUNwdGtDK2ZR
            OHZmaU5SYkV6RGxnb0tlUXZUUlZBUm8KLS0tIHByckI1K2pMOXdjUEtpR3RTMVJ4
            d0dzRzBvL0xSVUIvM2wxaTNxa3BVOWsKeYOr7Th1qLWPgCyOwMhnVSugVJkDYkrX
            55RapjoZgWd2bQ+T/MPMmth1IME1F43gR+mN0u++mTZ7U+5ovbUp/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:57:32Z"
    mac: ENC[AES256_GCM,data:WreCMB5bY0WnCd/TR6NLDAxJoCITsGwkOtRIJW66HAN4xwQvjjbnH+hW1lIB4yCUKGEILjTy+pnKrzOykntTrtpy5M6LlXxUs1guTbw+vtPLVGspCJLAM21pAcHHSQDrL7nEvgfllCCErOgsn6oBplgX5mOtYsD9SSCtTtjhZd4=,iv:HMSBDTFF6LInelL8AM9PQsmnb/p3zrjQ9w7aM6Zmu8c=,tag:P0sJ4BAs8xtsmYAXB618HA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
