apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../_components/wireguard-sidecar

patches:
  - target:
      kind: Deployment
      name: nzbhydra2
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/secret/secretName
        value: nzbhydra2-wireguard

resources:
  - deployment.yaml
  - ingress.yaml