apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      region: eu-amsterdam-1
      vault: ""  # To be configured with actual vault OCID (format: ocid1.vault.oc1.eu-amsterdam-1.xxxxx)
      auth:
        tenancy: ""  # To be configured with tenancy OCID (format: ocid1.tenancy.oc1..xxxxx)
        user: ""  # To be configured with user OCID (format: ocid1.user.oc1..xxxxx)
        secretRef:
          privatekey:
            name: oci-vault-credentials
            namespace: external-secrets
            key: privateKey
          fingerprint:
            name: oci-vault-credentials
            namespace: external-secrets
            key: fingerprint
