apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      region: eu-amsterdam-1
      # Vault OCID (format: ocid1.vault.oc1.eu-amsterdam-1.xxxxx)
      vault: "ocid1.vault.oc1.eu-amsterdam-1.fruyd6i7aagf4.abqw2ljrzcituk5pndpbgsvhtkgenvf2ae7xnlbctmskmcfj2gw6xsjhbgfq"
      auth:
        # Tenancy OCID (format: ocid1.tenancy.oc1..xxxxx)
        tenancy: "ocid1.tenancy.oc1..aaaaaaaaq7zpfzcaj4amfz7xwv33rlsopwd4m2ydhgjdidoan67vry5ejlsq"
        # User OCID (format: ocid1.user.oc1..xxxxx)
        user: "ocid1.user.oc1..aaaaaaaaqs7gnuu36fasrcmjjoxtrouwal4aspcewcf3ce6l33mdnjvixr2q"
        secretRef:
          privatekey:
            name: oci-vault-credentials
            namespace: external-secrets
            key: privateKey
          fingerprint:
            name: oci-vault-credentials
            namespace: external-secrets
            key: fingerprint
