apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      region: eu-amsterdam-1
      # Vault OCID (format: ocid1.vault.oc1.eu-amsterdam-1.xxxxx)
      vault: ""
      auth:
        # Tenancy OCID (format: ocid1.tenancy.oc1..xxxxx)
        tenancy: ""
        # User OCID (format: ocid1.user.oc1..xxxxx)
        user: ""
        secretRef:
          privatekey:
            name: oci-vault-credentials
            namespace: external-secrets
            key: privateKey
          fingerprint:
            name: oci-vault-credentials
            namespace: external-secrets
            key: fingerprint
