apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: miscellaneous
  labels:
    app.kubernetes.io/sops: enabled
resources:
#  - ../../../_base/miscellaneous/kured
  - ../../../_base/miscellaneous/rancher
#  - ../../../_base/miscellaneous/cloudflared
#  - ../../../_base/miscellaneous/adguard-home
components:
  - ../../../_components/resource-profiles/t.small
  - ../../../_components/node-selectors/pi
patches:
  # Node selector for all apps
  - patch: |
      - op: add
        path: /metadata/labels/node-selector
        value: pi
    target:
      labelSelector: "app.kubernetes.io/name in (rancher)"

  # Resource profiles for specific apps
  - patch: |
      - op: add
        path: /metadata/labels/resource-profile
        value: t.small
    target:
      labelSelector: "app.kubernetes.io/name in (rancher)"
