apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: misc
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - ../../../_base/miscellaneous/namespace.yaml
  - rancher
  - headlamp