apiVersion: v1
kind: Secret
metadata:
    name: headlamp1-oauth2-proxy
    namespace: misc
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:krHeO7QsmTRbKYw+FM5efsR9MUFe3ntbOMvq2Y3SjAyM77pjVBu2mVK6WKstmJFdD7Xi0A+9pr/zSqtjsFKFKipNvvT9lOEl,iv:XRJMICSCmARWQwBqiYNC2+YJPOjiWRsUVPQr+AeerTc=,tag:MoZ2AI6zn27aRz2YoY3MDg==,type:str]
    client-secret: ENC[AES256_GCM,data:umAiJNN5uUMX+TXX71zarAQZOxnycv1f41S32/ooPo6Y4io=,iv:lDHySiU5/NeSF/vJFHOtEAHqXbVWwmbPeqyVrL9o+ps=,tag:iqptuZIVRaQn1Q3H0gnlZQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:4w4RnegfRIzEFh2mlIndSvMEmY0bythHi9ALJZoChSPmVpGXXSELFMmHep4=,iv:JzKFx5f0xRNZ2kTSkUPORFfwC83wLZAXQ1wTsGYkHCU=,tag:cSSjUlui5XLTtwlB9n7vpg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RktOR0k5RExpVlIvMzlC
            bWxzOGRheTdBSEhld0thdElxU1lvMnR0SlY4CmFURS8zMUlJQmY0Rm04R2dXWlI4
            V3JETUEvQnd4OGVZTmIvNjAzaVYrM0kKLS0tIEprZThSbEYrMTc5dXBZSTIvSTVO
            MCtZVnlyNUNGZ0tvZnVodm94QjZsY3MKe874DzZD29DfUs+1X/NYqkjh20japyeW
            0lZlvRZcoIc1D+UUbKKJkKRviKAR0KfMBLgpJQQgOAJlRI8i1tyQxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:47:09Z"
    mac: ENC[AES256_GCM,data:x8r/1tVj3oAbbJo0fd2SZ/7NrZsqnseVG/daD3yA8QFrY6YahEEKyWqG+JOb4w9Mg4t7dr/gpgSko9z82F/INXuVV93c/uqOIuB1YZoVNkz66QO2GsrnSwkJhyNqPwXNtUZDahhcgXOoQner0pgAxKTNs4cQXwaKq+GqZ7GiQsE=,iv:sp88qaCqQWhdbDFgBf96hjfXTCGWtY2B36ruvvXbEew=,tag:lyic+pU9cF5BSUQtq6ycjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
