apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp1
  namespace: misc
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headlamp1.sargeant.co`) && PathPrefix(`/oauth2`)
      kind: Rule
      priority: 200
      services:
        - name: oauth2-proxy
          port: 4180
    - match: Host(`headlamp1.sargeant.co`) && (PathPrefix(`/c/p1-prod-eks`) || PathPrefix(`/clusters/p1-prod-eks`))
      kind: Rule
      priority: 100
      services:
        - name: headlamp1
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp1-inject-token-p1-prod-eks
          namespace: misc
    - match: Host(`headlamp1.sargeant.co`) && (PathPrefix(`/c/p1-staging-eks`) || PathPrefix(`/clusters/p1-staging-eks`))
      kind: Rule
      priority: 100
      services:
        - name: headlamp1
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp1-inject-token-p1-staging-eks
          namespace: misc
    - match: Host(`headlamp1.sargeant.co`)
      kind: Rule
      priority: 10
      services:
        - name: headlamp1
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp1-inject-token
          namespace: misc
  tls:
    secretName: headlamp1-tls
