apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-emails
    namespace: misc
type: Opaque
stringData:
    emails.txt: ENC[AES256_GCM,data:+3ilYvS+ACs4J0q/cDQ2eyeKwyhUWnw/5GGa0nw5j2aVwb1mKVp3fpx+TGf3ThkcLo9Bozxq17CcFfkHESumemlZ,iv:kWJN3Zy4+9LHak33MGm1ZnJaPIapYj27XUFOOvWTSRc=,tag:h/7CeWrn+YIV5JgqDx4/sA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRODM3QjlqaHdnZlE4Mnd1
            M0JocDdFRWN4VitSRzZUWTNjSDh0b1hTcVcwCnRWaDI3dEhoUHJaaHFvcXlYQVgw
            akg1dlpXaUtRbVpaaDh4cXBYcW16SlEKLS0tIDBGRVh5cUY4YWRUb2hwNXFsZkkz
            K1htQ1p1S0RBZmppdTBXOURoSzNabG8KoLOZ3bvPBrF+z3VGIGCVj48+s2y2540f
            xkST+6SkFj7SGs+L5xviitZxewRszDleuAUhvgYIMUqJFdytpe8ZLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:31:26Z"
    mac: ENC[AES256_GCM,data:1gmwZ/V184fquFmvaKOgSlfn44ER6MEsVQM8IaF+UB86xyvSNB308r0yCELyv/bxUVLn1Q0M7i1Nc/DXxOe2IRsn3owmqrojdIRitV+BEaP21gogJEB1mYZahTPgcYeZ1K3KS+AXTugvYkYS+sYgl85xDhs8Xx0eLGmWbm1E4pc=,iv:K8hN7T/3zu1+gtUqeeA3KT8OJSyV0rH2tN17bUHarEg=,tag:eYNYguxygFbs/7tb6b8/5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
