apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp1-admin
  namespace: misc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp1-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp1-admin
    namespace: misc
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp1-admin-token
  namespace: misc
  annotations:
    kubernetes.io/service-account.name: headlamp1-admin
type: kubernetes.io/service-account-token
