apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - pv.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - secret.yaml
  - secret-aws.yaml
  - secret-azure.yaml
