apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlantis
  namespace: automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: atlantis
  namespace: automation
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: atlantis
  namespace: automation
subjects:
  - kind: ServiceAccount
    name: atlantis
    namespace: automation
roleRef:
  kind: Role
  name: atlantis
  apiGroup: rbac.authorization.k8s.io
