apiVersion: v1
kind: Service
metadata:
  name: atlantis
  namespace: automation
  labels:
    app: atlantis
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4141
      protocol: TCP
      name: http
  selector:
    app: atlantis
