apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - ../../../../_base/database/postgres
components:
  - ../../../../_components/resource-profiles/m.small
  - ../../../../_components/node-selectors/pi
