apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: homeassistant
  namespace: automation
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet # Adjust DNS policy when using host networking
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          resources:
            requests:
              memory: "612Mi"
              cpu: "10m"
            limits:
              memory: "612Mi"
          ports:
            - containerPort: 8123 # Home Assistant web UI
          env:
            - name: TZ
              value: "Europe/Amsterdam" # Adjust timezone
          volumeMounts:
            - mountPath: /config
              name: homeassistant-config
            - mountPath: /config/configuration.yaml
              name: homeassistant-main-config
              subPath: configuration.yaml
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant
        - name: homeassistant-main-config
          configMap:
            name: homeassistant-config
# todo: move from sqlite to postgres