apiVersion: v1
kind: Secret
metadata:
    name: postgres-app-user
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:g4CX,iv:wmg+JpK8K/FxIoK/TXTKLc3+Cr/bxZ7bwBx4VrIOiC0=,tag:ymTmKigYUUykA1HKeA7Ynw==,type:str]
    password: ENC[AES256_GCM,data:ltpa3s1xInjMizUaRAhjusfYTHkKGBrb,iv:aHS5Ioq88sT/ZSSE1cKRXvPGY0b5nFRX0RdyR59CY4U=,tag:5dSANlv5VFO6/PxQr/bdIA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVW0zaE16dHY1dVNVdm9a
            SU1wbzZSczZHbU9tSWJZdnE0WG9JMDE2ekIwCnJ4WTJicllHRkJiMmNvTlY5NHZo
            M0N2NkJjOWI4cUJkbmRNLy8vWTVuNlEKLS0tIHdYcjduUXlOM3VyYWRRYkMxcFRW
            alhlNkM5aW5JdnNyUVJMd2hzdkRFK2sK4CzzbnZcEohuRtIyTF7IMERn41za8s8o
            YAewroTka+jQlhjVMTOYqlUbB4yKeXgoKHI5HQjvu+dHUGfu0RZqIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:34:00Z"
    mac: ENC[AES256_GCM,data:kI3h/tWgODWq72/8GWkQyfwEj9bZh+2dVyIgAQPJZs4tVQ8WP9HGcDQ5Jf3+/LvZ27fqnwILj1F3MkmcXNL3l9Da+KbSoVcYCv0ZaHdioZ26JDZxlkgjvpA0g7Yfn7ewiZtdlWwVV8aHTeWmkoWk5sE1FTzDZVOcn/9KY6pDdTo=,iv:TfXfPs27+7/34T084H8k6EOj1AIJd6GU+9cBghVAwFQ=,tag:cXndVrOqt2dqFmkbRye2Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secret
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:zxhJvLwUarE=,iv:MfAWH6Dm3mYQ2u1ooPbZb7qzjxLuZgm3aV82qpeLzMM=,tag:nGVUCNW5qGvVZO0hlKi7qw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:S6r0ROCjVIXww/Lk269GlMwHOO87uYJL,iv:m6ebx/pw1uRtujcudWhIKhoA8/QMDLDTmhFLvVcdVFI=,tag:BRBnS0KsVspNkj/iudKNuw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVW0zaE16dHY1dVNVdm9a
            SU1wbzZSczZHbU9tSWJZdnE0WG9JMDE2ekIwCnJ4WTJicllHRkJiMmNvTlY5NHZo
            M0N2NkJjOWI4cUJkbmRNLy8vWTVuNlEKLS0tIHdYcjduUXlOM3VyYWRRYkMxcFRW
            alhlNkM5aW5JdnNyUVJMd2hzdkRFK2sK4CzzbnZcEohuRtIyTF7IMERn41za8s8o
            YAewroTka+jQlhjVMTOYqlUbB4yKeXgoKHI5HQjvu+dHUGfu0RZqIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:34:00Z"
    mac: ENC[AES256_GCM,data:kI3h/tWgODWq72/8GWkQyfwEj9bZh+2dVyIgAQPJZs4tVQ8WP9HGcDQ5Jf3+/LvZ27fqnwILj1F3MkmcXNL3l9Da+KbSoVcYCv0ZaHdioZ26JDZxlkgjvpA0g7Yfn7ewiZtdlWwVV8aHTeWmkoWk5sE1FTzDZVOcn/9KY6pDdTo=,iv:TfXfPs27+7/34T084H8k6EOj1AIJd6GU+9cBghVAwFQ=,tag:cXndVrOqt2dqFmkbRye2Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
