apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      automountServiceAccountToken: false
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:latest
          ports:
            - containerPort: 7575
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: DB_URL
              value: "postgresql://admin:s78x7jKMiWWNpdd@10.42.0.35:5432/homarr"
            - name: SECRET_ENCRYPTION_KEY
              value: "3d35e307db58a121aabbb21a444906467510869bc6133952392defbe31e15930"
            - name: DB_DRIVER
              value: "nodePostgres"
            - name: DB_DIALECT
              value: "postgresql"
          volumeMounts:
            - mountPath: /app/data/configs
              name: homarr-configs
            - mountPath: /app/public/icons
              name: homarr-icons
            - mountPath: /data
              name: homarr-data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
              cpu: "200m"
              ephemeral-storage: "2Gi"
      volumes:
        - name: homarr-configs
          persistentVolumeClaim:
            claimName: homarr-configs
        - name: homarr-icons
          persistentVolumeClaim:
            claimName: homarr-icons
        - name: homarr-data
          persistentVolumeClaim:
            claimName: homarr-data
