---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data
  namespace: syncthing
spec:
  capacity:
      storage: 100Gi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: syncthing-data
  hostPath:
    path: /mnt/nvme/syncthing
