apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp1-tls
  namespace: misc
spec:
  secretName: headlamp1-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - headlamp1.sargeant.co
