
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  namespace: misc
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    traefik.ingress.kubernetes.io/router.middlewares: misc-headlamp-inject-token@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - headlamp.sargeant.co
      secretName: headlamp-tls
  rules:
    - host: headlamp.sargeant.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80