apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: misc
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headlamp.sargeant.co`) && PathPrefix(`/oauth2`)
      kind: Rule
      priority: 200
      services:
        - name: oauth2-proxy
          port: 4180
    - match: Host(`headlamp.sargeant.co`) && PathPrefix(`/c/main`)
      kind: Rule
      priority: 100
      services:
        - name: headlamp
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp-inject-token
          namespace: misc
    - match: Host(`headlamp.sargeant.co`) && (PathPrefix(`/c/p1-prod-eks`) || PathPrefix(`/clusters/p1-prod-eks`))
      kind: Rule
      priority: 100
      services:
        - name: headlamp
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp-inject-token-p1-prod-eks
          namespace: misc
    - match: Host(`headlamp.sargeant.co`) && (PathPrefix(`/c/p1-staging-eks`) || PathPrefix(`/clusters/p1-staging-eks`))
      kind: Rule
      priority: 100
      services:
        - name: headlamp
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp-inject-token-p1-staging-eks
          namespace: misc
    - match: Host(`headlamp.sargeant.co`) && (PathPrefix(`/c/pr-nonprod-aks`) || PathPrefix(`/clusters/pr-nonprod-aks`))
      kind: Rule
      priority: 100
      services:
        - name: headlamp
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp-inject-token-pr-nonprod-aks
          namespace: misc
    - match: Host(`headlamp.sargeant.co`)
      kind: Rule
      priority: 10
      services:
        - name: headlamp
          port: 80
      middlewares:
        - name: oauth2-errors
          namespace: misc
        - name: oauth2-auth
          namespace: misc
        - name: headlamp-inject-token
          namespace: misc
  tls:
    secretName: headlamp-tls
