apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth-p1
  namespace: misc
spec:
  forwardAuth:
    address: http://oauth2-proxy-p1.misc.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Email
      - X-Auth-Request-User
    authRequestHeaders:
      - Cookie
      - X-Forwarded-Method
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Forwarded-For
