apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: misc
spec:
  forwardAuth:
    address: http://oauth2-proxy.misc.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeadersRegex: ^X-
    authRequestHeaders:
      - X-Forwarded-Method
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Forwarded-For
