apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-errors
  namespace: misc
spec:
  redirectRegex:
    regex: ".*"
    replacement: "/oauth2/start?rd=${1}"
    permanent: false
