apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-errors
  namespace: misc
spec:
  errors:
    status:
      - "401"
    query: "/"
    service:
      name: auth-redirect
      port: 80
