apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: misc
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:2aL48bvxA3isUOzcvz3d+kJLIwAZ5SeAWXYdJAHrn1W22PP9gdeiPwUY3H1Neu24JHYrYlva0o8gq9BymaPgaV64BqfMRli7,iv:udjwdtIsui4D9OlccHbB6GKHN8TkNSmn9OFXW8R4oT0=,tag:P1kKAjrXGEYOd+jsQgviWA==,type:str]
    client-secret: ENC[AES256_GCM,data:7LU8ntzSo7AdiS74HMMOvkkcAScThsvLG/3VfrMDU/jSU7c=,iv:XANXhvNweXwCERNg/Io4gYcXVQ4el+Xdi3OSulWcac4=,tag:vaec4h1fGxvTDswFELUa/w==,type:str]
    cookie-secret: ENC[AES256_GCM,data:NHhHpNo9IVQxncu6DNOC4d3jTb/6P0qzrFXk37ifF9o5/T0L7MKLN7/8Q2U=,iv:PzmnavX+taSwPd1IH/75yfEUxdhbyv6J6t2igoN5TC4=,tag:pxnFqzDxSYnTabKsxPf3OQ==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ01sdHl2WW0wNGc3cEdW
            T1B2UmJjWm45T0ZTMEk4cUhMcng2TDRqSUdVClcyQU8vZ2VqQjRsdjlkUjViTnR6
            NlorbjN4dHlhOFJFdlR4UmtWcEpETmcKLS0tIE52SG95cUt1dUI4ZElxV3FIem9Q
            UTU2NUIzUDVHMnovUE9Fdmk5a0JnUU0KgNaE4XlDTw/yCdsRW/fO8GloPMz1UgaO
            Fw5PWuAsW9HaNWgcU2FgTOlNeH1p/wYAA8SESTv+yIWIegit/4AvIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T11:20:28Z"
    mac: ENC[AES256_GCM,data:oAo8MAW1HMDrs/0GVElaywzESeZ00roOZL5/kp3b7dpGvYKkeBXqiRZZvS2j16pVRrOTvJqT+j0olsjVLlLIpmdboIuZJXWPC3hXqjZ9ju5+0tXKLmTNMKBbkdmmliAAwagPI5d+2zctCs5s9W410yRCqQbNkRn4Ko8U1iuAdHo=,iv:UUqcynrbzhCUw2djQohPs2ASFOv+LIQkiH0/Izo0Jec=,tag:oDt5psUNlpjQ9StVm/0cRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
