{
	"data": "ENC[AES256_GCM,data:fc5ZxmlwkrXlCQBDINyF2h3hDkSlDQH5fF82Cf96W3i5UHvZCR79P5osUqgNlrPwU4rzvhvBErQnd6S4vDX7jiOlzBzv0bnH/Mx+34MyWnuqQdnA6oKfsX5PLndk5wW2vM5+ArfzYb3/pQpal95UpaO4HfM/RCArvStljFwgEpD91oaNp3b3o9uqpI3jj7Ci/dg7yKWP/FJxaTn+N006Xq2ORmjBlBNoWtfiguAMedO/ojJskixaQJO37y+bLI/c86wIT9BDwUtn+P9/HdwYALdOLpsAH7s/9qwMKuzC7vcl53I2RKPZMzTIcxo2jn0HSNU0zX3Xb5MEv0c5uDUOC3KLLEN2ReTftpGVaBCvYqMNz7IGZeE14A27ZSUf1CG+z9ejQUeWrdSZz05MdKJoJ0CIB9DNlkhYjN25KA==,iv:DBQtRxtn5ag2dbLx5BUciIGdX+EfzOoYLFzTeYCH12A=,tag:RjPHLhdw3F7SLC9mP2QwxA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TU14LzN5c09GaVQvdEVH\nSlhaaFhMcmRtMytpcEl4MVRzOTJRZjdpWGpvCkdrZm5obkdLRm1YUno3U0F3dDFv\nV3FYNjVvR3cxQUNyVzlkMXRlRUtzM0EKLS0tIE1SY0RXYjh1LzExNy9iRFZ2b2VI\nU3B4dHdJYWR4ZjNIVHVYVUkxQk5GdVUKytHk6BjhGFTodWvsFkfa2eqbaExnjNho\nrjSC9U3L4xr6fbP/X3SnePJDDuexdAyKC73pI8UGqsBPdi8HZoHvCQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-01-20T20:44:01Z",
		"mac": "ENC[AES256_GCM,data:ZI0XG4j/+LnJau/qGe0ZLLF1DOw+V8Eozj8YvdqEF810g+Uh/ROgEll9oOjPHxalB991EdLSbddjLUS5pyZpKcNl/LlA/iRzqbwqNx9yHa/FMGWCsYaczKlSwDyPMC8/V5LljWhjvN67VRb22NavHsAikPREcWcmEuSZKf8vUQ0=,iv:KmP81UMMgbLm27KDaJsDjMylf3rKt9UBeYSYfp+sMyg=,tag:phOyd8sx04PZMGHk1C1olA==,type:str]",
		"version": "3.11.0"
	}
}
