apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-p1
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy-p1
  template:
    metadata:
      labels:
        app: oauth2-proxy-p1
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        args:
        - --provider=google
        - --authenticated-emails-file=/etc/oauth2-proxy/emails.txt
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --cookie-domain=.sargeant.co
        - --whitelist-domain=.sargeant.co
        - --reverse-proxy=false
        - --skip-provider-button=true
        - --redirect-url=https://headlamp1.sargeant.co/oauth2/callback
        - --set-xauthrequest=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-p1
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-p1
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-p1
              key: cookie-secret
        ports:
        - containerPort: 4180
          name: http
        volumeMounts:
        - name: emails
          mountPath: /etc/oauth2-proxy
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 100Mi
      volumes:
      - name: emails
        secret:
          secretName: oauth2-proxy-p1-emails
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-p1
  namespace: misc
spec:
  selector:
    app: oauth2-proxy-p1
  ports:
  - port: 4180
    targetPort: 4180
    name: http
