apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-p1
    namespace: misc
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:/H36xquvlVQ9SSnnvTJovihrDkT56POsVEWKIeJy6TsP+wnY8IeIKAaTPwjYKSentRctmdYDvAL2qVGnPixZkAQp+owR7SWB,iv:RKhkpTrYtPKY+OZHiokGV38ZsP0oRfCqcSTfQeV8Sd0=,tag:9+AKXdSlmdvgJxiPXHOZGw==,type:str]
    client-secret: ENC[AES256_GCM,data:e9P7uH4f05IwhbXr95uoYDZ45wVK1pVUJkGdU+q53GADyN8=,iv:wlotxHy+EVazRlTk/6X8H8MIrBaZpTGaYfACWFQjFQM=,tag:xkDFjkda1rudymQeJ8+coQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:q1qyo3uQ/bSIPDyPC7oxhNaeMDItDi9/EPIcJ5PsoulfQC3nS9MiO8dzR/s=,iv:bjj4u2t4RN6YjkBB7Qp/WlnqUDKfKRnBo4hCQjViNXM=,tag:PBQ0kKSwX9+RZkhzi4yGbQ==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZi81SXZ2cTAxbnlnTklz
            djQwQnF2MTR5MGxhWTJaSUhVcXdxOTFyOUh3CkprRjFibXRUell3UVZKRGJWbHRo
            dmxiOTVCdGF3aVpzSTZqaU1VMzVtZzgKLS0tIEtvSEIyMUNVbXdEM091R053aEdQ
            ZkZUUWpwMEo1MzFzamxsRXhuQWg5dlEK5iyXs/TjhmheEQSOTO8aUKuf8fehDzDf
            VYvpXfVIdthxvBMkX6Xi/Cqg5safsnvl/Fqn4NzuygLEaVUu/lHvFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:52:23Z"
    mac: ENC[AES256_GCM,data:fEWZQ04mzEUwTf6Q1ejzqFTu0AyEiuqLq0hVAHTF7aU/WhFcIkp1s9zVvA75Xm+nJXuZwzydFfIs5oCNZLDUuMfi+mIIQ32egWdb9aYCGp/WOFaVI1YAE8Fgwkf9tRJW0KYGgvNtvqzvUpFGG8NweNC8EnvZOtkjWBGXik9VB98=,iv:zYVbkK/L5tgW4QXgOwk6nf2T9jSUfMLnofllg16TN44=,tag:w3HF8qrsoQ+WgfRWTpkEaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
