apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-emails
    namespace: misc
type: Opaque
stringData:
    emails.txt: ENC[AES256_GCM,data:/hSrTHdUjdaMpymYjbvGRjhvndevvwM70Fkvb3wOuBAJPIu6RMJZFpghTT8kFziEc09nzgebWWduFuDdqF53rvlG24d+dfQjuwIUuqpnBS3gzKcqDQ==,iv:Gi4F4xkTRzUwFvGH2ValCgcwD5IDV1hvWOIwC4WlHCI=,tag:NxNL3nx/pCMw4XmcFZ+Nmw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQm9GWXdYUjNQN2ovWEJV
            YlNwSXJ1bFJ3QkxXT2FoenNHQzcvOHJ0SUE4CkpDb0g3SHk4VWlDNHZ6SWNuWDly
            SUY3RERqdEViRHgxMVh2akM1dWxJcGsKLS0tIHE0dDJPL2cxVXBDTnVseVZqRXNY
            T2d3MDBZdTl1dFlvQlVueE5WekJhNGcKKQsZ205eDYOD/0JG6F8YmvkMnMoum0ii
            AMCl6Ljzm5mRRQQE2tTH1P7F1wsOeArvb4um5FzfZBkx205+enOVKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:03:01Z"
    mac: ENC[AES256_GCM,data:DoHR7a/FMALHzwVNerDmPsh3MOjkN21S3HJkfViIL1A0z2Xz8l1qUhyOkbReOtbJVHjn0rQ3GCqqUp7RKYR8hO00XpjrB3NMaLFyRyfyaCgB8naWpKCvZ5tAvrEPJca7VNdTtJ9Z2sMjBUo8VCxQp+se17/napNcZve4D2VokEA=,iv:wSBuKd0MhuAdE1l04SmupR2EiF61ZiCO7xxgiQbD8Kk=,tag:jcK3QayW6y5sa9aPVrJcJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
