apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../_components/wireguard-sidecar

patches:
  - target:
      kind: StatefulSet
      name: qbittorrent
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/secret/secretName
        value: qbittorrent-wireguard

resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - pv.yaml