apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
    - name: web-ui
      protocol: TCP
      port: 8080
      targetPort: 8080 # Web UI
    - name: bittorrent-tcp
      protocol: TCP
      port: 55555
      targetPort: 55555
      nodePort: 30555 # BitTorrent TCP - accessible on all nodes
    - name: bittorrent-udp
      protocol: UDP
      port: 55555
      targetPort: 55555
      nodePort: 30555 # BitTorrent UDP - accessible on all nodes
  type: NodePort
