apiVersion: v1
kind: Secret
metadata:
    name: n8n
    namespace: automation
type: Opaque
data:
    postgres-username: ENC[AES256_GCM,data:x9d9at6C17JvKdjwIfCKqg==,iv:X4C4t3cEhWZHmOJVJXnZT20X2L5FjFTjI2+kF4ZSeRk=,tag:fYDlgbYjwBAE38AVXAD2pQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:FAy/c5yKQ/qTE+EpzCPuhOvCbWuHpBaw,iv:gsnCyuQPbqN30+BhCvjiawxnoQOLclVxnZHpSOUGx7g=,tag:VGcaqJTNLA2TXTlFT4VFIQ==,type:str]
    encryption-key: ENC[AES256_GCM,data:FrB0d6HlgzjkwYLtxFYm7dvZjG72PJhy7WrVRpwMG4bqonWOLXzkdgDexiar5s2KdzpBMY96uQGYAKfKawY9ght4j46ks6i+SkvwU1ZVVnEqMsthb4eIMg==,iv:gQqX4jgW/1PYoZu7RvVlxHWJZkyoaFjp0k4eLBgS1Rg=,tag:Re8x29k3FbY/vI23EtjYdA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmUwTnVud2VRYnJka2hF
            VkwzNkYzQ0EyNmlnOTVtVHYzQWREVWE1RHhnCmZ4SFNCZys1QTNhV25TZ3lnVEl1
            eFhJY2VCUnVBbUF3Mm9UUTZNRE1UQ28KLS0tIFIzTlVONFptSEczR29XM1F0aG55
            N2FtdjE5c2tWMDNzMnVtUmdlOWtuUUUKF4KQmEFbAZX22EdBHP1V7MeCX4EbETXH
            gMp+DuGm/05JxNzqiJGbj5+jM25vY/YPAtMPCECDenHmNAxADCa5kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:30:30Z"
    mac: ENC[AES256_GCM,data:uhPdRo/ItYV1kJzZ6E3Nr44MOxbePixTU+WbqTcZYhtNraINKzzCbNI3vjeIL+xTB520AlSJSDB3fuo3rplQC0ihwmWcJ15cY5WPPhuqFIa2To3Ojo85U85d8lc+/c9ZpO1v/nvrbGWPoGNEAa5AWwQlFKyNbufcUV+l6tgtcJk=,iv:H0tKDmreab3Ynf30PyWacZoTPqXXRVYoupd0eNBuEw4=,tag:Zgq5fzlBtygZsGBRh4mLUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
