apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflared
resources:
  - ../../../../_base/core/cloudflared
components:
  - ../../../../_components/resource-profiles/t.nano
  - ../../../../_components/node-selectors/all
