apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:6PhHWnXI4++W6p4dq6pdTVBlmYg0lmGtKa3mnJgWPaRezKngVI3CGnE8TZn3YsXcNOTNZFCt4GuZMgwtbWGL77AhW9Cy5AqOK0yhlqASzhlBg2RYsMhD/cXHzj9JBe0XmudngEOp/00RBHZeXCyeCWbzU1MffesJ1ooyTGDmoQvBRr1IrtudHJkC3M/JJM+3BfSTu/lIKr6cSJ+JVHLn+k8xf61olIcUDsEdlTgmI9cLII2HdM0FtJZgQGxvVPlYKz9atLalSg7X6dBFK6DrckGfgbXSZ3CgDrlPyD0gi25FbTwJcDTPuKGTkk/OH0SjSL3KyKKq00nURL3KuqvLd4aV3jlfj59pBDnIjnUlE3tVSIIRR38S/05JTWntGpau4Zd8dDEpoiRlqis92tTtdUc0DKOEHBUvPqv4+ogDXkZNVVTUuKFtRR8NTRWjArmOvebJug3CZNEmg21sucCXibh5Wv7SVrU0RShjQGL/PQD6eB55wahC5AlCJ4//gdkH2NXvJM4KnPqb2aZLZSC4beas9hfrqT8TLbfApGHncoINVd1108sLnI7UU0liATphwZnzZO+4oGu+jvOJxr4gZHH4h7e8PhXyeJbZG5Ca7nwmH0pBh05fjsAmwewOX+DQyPgxwyT2cjJ/zAUZXZ0FBCX1ZbWYpmnzLrxKjNDb6b6cU+wg,iv:Q052pbOIBYA95L4vM70I5ebx7sN2z+fnXOSGBTwyo0w=,tag:ZjCA0rCvN6Hf0puMK2LE7Q==,type:str]
kind: Secret
metadata:
    name: buxfer-sync-deploy-key
    namespace: flux-system
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ODYvYW9FRFB4TjgvR3Jx
            eUd3cXVXN1czYzBFNng5V2RuL01EWm9HczE4CllsTXl4OUFqc0trSHFWOTBTcWM5
            NG9SeGtXRk1IN1o0ZHNyWFllUU5nMWcKLS0tIDJOTWt0OXFLb3VwZzkwUjkvOEdi
            b2RqTjk2NXlVMTNPUmwrNkI3TEpRSjgKK0TpO0Q2U5D/FRCheve7+B73m4ak19bL
            HUoS1PEy8lz5NB1Y5I5lkX4JzCEByo3pHzVYFuvXjJ9YHyz3ELNhAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:02:14Z"
    mac: ENC[AES256_GCM,data:HyDlEsNhBy1c1EJoyEUgoq/568fQHgK8umVLfKbT34mRqnM2KHdSKWDtLZOrydETWglvVVVoPTgBXo3xryDOUGS26SZMt4XS9//gGMccyX++JNlFc1AN28pDSvj+STy2s4/CfUA8r4U9Y98LcwqYJuSljUAgLi5MsQR9Cm2YBnI=,iv:pGbBak4gIV659aZ8t9A03sadvzfV+1Lg76tkRK/FhTo=,tag:R0Ryqclq0oDmZ1wrbUprRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
