---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  interval: 1m
  provider: github
  ref:
    branch: main
  url: https://github.com/CalebSargeant/buxfer-sync
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  image: ghcr.io/calebsargeant/buxfer-sync
  interval: 5m
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: buxfer-sync
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$0'
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: buxfer-sync
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: actions@users.noreply.github.com
        name: Flux Bot
      messageTemplate: |-
        chore: update buxfer-sync image to {{ range .Updated.Images }}{{ println . }}{{ end }}
        
        [ci skip]
    push:
      branch: main
  update:
    path: "./k8s/overlays/prod"
    strategy: Setters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: buxfer-sync
    namespace: flux-system
  timeout: 5m
  wait: true
