apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:efWnlUE7s9Eb8MTCf+jeYi2sbS6HbhoemI6Yuv3AAT0STVlYdmdfpjBBtcYXY4+KA7IvOXRNg5H2yxfHHBi5DiKRrnh4d4VlUNurshZZLB7J/zJ75TSZLaPrUMyY0Wwo1V+pSYTrnQO0ACFtcARY5qdqxyg0alwTPTw9ULiGz5Ac+b9SCK3nJCENCTGyTXFLfV/hGteDiF69fG/Ncrl0AeFILT2x5wODP3ObILMU0EbSh3Z4HtJ0oCfTwY1Vh+1myS7Jm7EFaIrb0oywm6qkP1UNKkNPzdQ3H+P9VrYNFf4iK6qOx0C8RJwbIiEnyO5n1fw2S6bOMi9NJemAplY98l/b52A6B0dm9RhD4WoNKxFrSVYhCaNUVDXtv9ZRAXrpsuYNOkxaODD/2Lmjs5mHvjbiBwFKuW5JUOFDjR5mvC5S2lGHHbXzLHIB0t3WaHqBK0QWU2W+Vmqpcg6leEuZaEpukbxgkRy254EohOlCFsXqXj113EUS3f9yHQ5FGCc7oLc2wqo6RDo87wLOJEhtCxF1h15MjdxYwragTl5DDUzAVfG4CJoGt8C2x2jfJ9PnH9AjOsqx/XCAndhIWOpePL6jdYilD51ob5sbtZ6Or+ZW6e54QGIXcMojqk6TYH7mLbWUgHpUojimwXkK83PWSG5+e88ii5DMhFQ0aib+wvZ6bMYB,iv:DbHUl4K3tQUaeW57ho04Fxi36sncuNnQeVe7+iyk5kw=,tag:j7z2LMbzaXAF/LESGOwiIA==,type:str]
kind: Secret
metadata:
    name: deskbird-booking-deploy-key
    namespace: flux-system
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K3pXMEF0OHQvWFhvOFNL
            WGN3ZlFkalllYldBeXNQb2NaVGNHY1FOOUhFCit5S2VXdkZZN2o1ckpDLzdqbGND
            VkRQYTNlNU5YSWlwY2FPQmVRV1FPSG8KLS0tIGFsUFZ3WWVFK1NhRUtyenNtY1Qx
            d29hbGdVMkZ2a1diQ1FKcjlFODRxQXcK1w9fM5/19yDBN3s/u9uW13AG+TV8OWny
            GQEKYBooXVt4HGKb7yzE78xLvVGm4C1aKA8yQfdOIS5eWbBTNluF8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:02:19Z"
    mac: ENC[AES256_GCM,data:CaW3lyG79OdqjCDmeKMlvtXyH4ziaKX0JMs/2qInNRWtXzdXX7dszsYtZl/lrU09QDM6RgwJ0cNG0P91qKKj+y9MjTK7JFsY2lStTJaDEyqYW5kiH6hHke99Bq4IuAf4rf+S3eMxKQ5bD/36MuPZB0HRaaXbZki6Hpe+ifdE/Zo=,iv:g3QgbiPlsNi1Gz1ii+zGa32FDz9OMyhgJ194P9laIeI=,tag:FgZbkpOolYjsVnjlz1P35Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
