apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CV9scgqNbCwtd8coLZl/SLl+W/pmv1WwgwU87uYudsxv+stu/YU8YZG1hR1PomXYAOJyRetvupvMoSkY9mAlvKwSQqtV7AWrm+K0gZKiT4aNwxBoczODG1d8MP419v1JdhEcitTkG/bi4EUBeart1ACbE5099vOCkQwVLoA/5+ftM0f0y+DavcbJ7VJAeDXazlid6H4yU7KcHLLAHjXBQKYOvg3JdnLXxuFNn/ldBsJsX9VhQecTlLWxO/jsp2O/ICFrq7sNjYTwvEB4PtijNvROfhSogxMU5HyI3Wgz/94nJ76kcw+kl4aVKtkBQQLzkRVNSSUXVUQ=,iv:8qWc5cDOoRPxglM6nyhBpAFGV7pDHqsYhgkFtPW9nkU=,tag:UhtkHzrGIpO1ABnpteJk0w==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMXhNcTBXaWJBSjA3aXF0
            ZFloMDA0ajkrRVZ0WkJVMHgxY2t3aUhwcERzCjZ1aXZ0T1A3a0hOemEyYis3THgy
            SWtJbmN2MUg0Uy9aVGVvL1U3RkNteUkKLS0tIDltMEJnRnlWMFZNZ3ZodVBjR2hl
            b1hha2lHY2JzQ2d3UE41dCswMXV5b0EKohUGaG1QLyB4nb/Bt0ifbd3rgb3H8t2l
            Q3zTBmhK2UTcy0vqYKsoZOx4tLy7UKzja6kHEF1hMnYgO8bE6FYHQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:51:43Z"
    mac: ENC[AES256_GCM,data:YQ9T5KBH+FLxSW4Bag4Qn+Zy3yuvdCjq+t1ueFPZrtQ3KSZDM9kLRxOT4nPazj8VIghkunP4cehFbRcVva0P2aS+yBTzUXD0+rW4ZvVNxx0DhuFmzp/T/HrqOIhjmBaSHr4o1EZhNBiEsnA6wqh/6QaCXiDF4YnileML3RRTu7E=,iv:HYKRIbd/y78LxN9h5fHrpwg1/kxNZbb0lk6e4hViIhg=,tag:aNFt9IEiL+xcuPHFW0akIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
