---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: git@github.com:CalebSargeant/buxfer-sync.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deskbird-booking
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: git@github.com:CalebSargeant/deskbird-booking.git
