---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: buxfer-sync
  namespace: flux-system
spec:
  interval: 1m
  provider: github
  ref:
    branch: main
  secretRef:
    name: buxfer-sync-github-app
  url: https://github.com/CalebSargeant/buxfer-sync
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deskbird-booking
  namespace: flux-system
spec:
  interval: 1m
  provider: github
  ref:
    branch: main
  secretRef:
    name: buxfer-sync-github-app
  url: https://github.com/CalebSargeant/deskbird-booking
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fortivpn-gateway
  namespace: flux-system
spec:
  interval: 1m
  provider: github
  ref:
    branch: main
  secretRef:
    name: buxfer-sync-github-app
  url: https://github.com/CalebSargeant/fortivpn-gateway
