apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: calebsargeant
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.calebsargeant.com
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 1m
  url: https://bjw-s-labs.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher-latest
  namespace: flux-system
spec:
  interval: 1m
  url: https://releases.rancher.com/server-charts/latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/dashboard/