# AWS Credentials Secret
# To enable AWS cost data, create this secret with your AWS credentials
apiVersion: v1
kind: Secret
metadata:
    name: opencost-aws-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rt8B39TPF5Zy6riSWO15YIfl,iv:gAgx3ILQ5r7aKHqRxhC3aBeTzke5zso3YePu8KA8F48=,tag:2nBQYmLwZupmjxFa0n1naw==,type:comment]
    aws_access_key_id: ENC[AES256_GCM,data:YiPHJRNyF/Y=,iv:p046lN/XetRYLWxfFAakNIxq8YcYTNQ1U3BsQAuVNDY=,tag:l98SK7t6qov+5u18ZkYcFg==,type:str]
    #ENC[AES256_GCM,data:CUTYfjA8no1K3v+QYlNLedlaBsEfYQ==,iv:UCy41LCycwfQ4JdiyptaAxzG0sbN6crsedYskDgyT3Y=,tag:YH6UmlAjtQctpZEhVwCWuQ==,type:comment]
    aws_secret_access_key: ENC[AES256_GCM,data:qdN4whXxcaA=,iv:U1tyzACknPUaY9GYUBFBGzmoIclq8eXzyxgXbrlsLKU=,tag:KVz8jkXBksaPuwsrusFxfg==,type:str]
    #ENC[AES256_GCM,data:HSXiA0hmClysO93cc0xzTiOR08al/3twNkKGUIfLRcMUME/o8Ss20g/+9uPx,iv:xMqu7K/mGQVPoGmO5aPGKRibF5iVD1dax+NzWo1B3F0=,tag:wiJXsej95GERNeBqNMJ4DA==,type:comment]
    #ENC[AES256_GCM,data:xtTaM3SsK/u8ZMvTD8hR5Xm85tpd3g==,iv:Xld8k0VP7braMzNXBd4ilHhfTIKSz93zzj7Ch1ndR3k=,tag:2EEVeegZc9uTe7aolBCtfA==,type:comment]
    #ENC[AES256_GCM,data:jKPScn853YCOF3nss+3dlDepgzyPH+JGEudefv07mgMvI7aCaGXMcOtn0P3c20eU,iv:vjRIuno3RmCL7zXpwOQL5xgDwyKI7C1cxDrfmwGyi9g=,tag:VtjAmZ1PqBy7nklAEv3C+Q==,type:comment]
    #ENC[AES256_GCM,data:6bjxUh4c4fKCf838bZWRwNKjAp/+Dj24xaw+r7nHOx/PHonr6NmgrhAj2RW7afmj6MekYLz83c3DWg==,iv:FKgdDrjso6DvfawzOLgkmIBJmgmKWnXm42y369N+HrQ=,tag:IHouqL0ISN9+R6p87b3fPQ==,type:comment]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMU9hMEF1TE81TDFsYy8r
            b2tHZ3ZQanVydXV1Uk1nUUdJUDBQTXQ4UkhjCkplUktlajlLN0RKNU5GRVpMenJv
            bzRqSnB2d3dsMDJOeXpNNFRBVVBOSkkKLS0tIDdDNHJrakhWSHloWTB6VHp2ZTFF
            TXpVMm4wc2dyZTB3VEwvdFBCWVFuN1EKbpPZL9PsRWJS5g9Icpk9Fm5oWrRgMO/Z
            2Fwp0a28sgUDxqELrKUOV5UGiVhpbZ5aMIHdiSqwJpaS+KEc8fb8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:35:45Z"
    mac: ENC[AES256_GCM,data:vjWvnGIvLjUCeN7AyZRU1H2zMvdFWJ6/lmZcq5gPvnyKnQ+y93Bshg2wz1u41rcq8tnmYxHAAacQB4VOhF6LaWLw4M65+z3wsY0tb0UNTyr1SjNIfov/7GBDdGwL5HZApyQUVeCp8vSGn2r28a3rxhmXhEjL8Jyqz/qPv0YK/dI=,iv:Eaanseeqhx05ALo1lLhiaK5n0Vj1mh8Yyl3gwSULKpA=,tag:9IHd+o1V4xTOe5Y5kfMozA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# GCP Credentials Secret
# To enable GCP cost data, create this secret with your GCP service account key
apiVersion: v1
kind: Secret
metadata:
    name: opencost-gcp-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9qtxkQmn7XF5umFpmuqqZIGVKbbyiDAJqbsPJqM=,iv:QUOKc3LAr8sEdHEMp0drsQwlxh5B2SAbxwt0W/cDa8A=,tag:5YiOnrnl63ARlztLJxiQwA==,type:comment]
    gcp_credentials.json: ENC[AES256_GCM,data:086/y372lDSiAUxSEvpI3s4u3KENJaAVCyq3zZCt/H8ub+qkdTTrVzyNHk2qe3a8Mvj+03JFjz/S3g4o2zFLQ65MQ9bLPdy+baG5pdslHDds1B3yXe9R0Otf7Xn8hYEIzUQobk77LYDlBSDbZhUD+9g6Vcd0ApfBuAT0BewJ5KCZ36Uy0ee6nkKaIsc7lAQlmWd/zDUSzDbg/fkUfrpZgWI3cDo58L4IUhS7M7ZRwFp5pZRPDXyH/ycVSoYvPiAwt7XlQRdjDA4em176LIsp+JPEccVDVlwOsJxPN01hZJjBGPA1nMp6d2d0dzIm1FU8524JdJry59FIF/EYRMBVEZBQJTPqNbmDWyGXNhpdhgFBGBcjhgKnouiNkd/j6jGQ2aeF6kZQKX35CikFmk9SKLTZ0WtbZ5E3PZXwUBgjVFbtdsf+TpPim5FK1BL2d9wrXaLCihkF7ER1/lfVk+fsqZsQIP/WHsxHya5Bey9IrPD0uLJyUl6Z/oNe9LNcKxeKjT4WmddE0il2yzOB8K6uYT/xdow8aR1d,iv:HHyBs/3RTkOusfD5+jxC3nMpIxP+qpnp5+3i1xY/t14=,tag:mzdQ7Xw0v5Se9wfpb3chsw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMU9hMEF1TE81TDFsYy8r
            b2tHZ3ZQanVydXV1Uk1nUUdJUDBQTXQ4UkhjCkplUktlajlLN0RKNU5GRVpMenJv
            bzRqSnB2d3dsMDJOeXpNNFRBVVBOSkkKLS0tIDdDNHJrakhWSHloWTB6VHp2ZTFF
            TXpVMm4wc2dyZTB3VEwvdFBCWVFuN1EKbpPZL9PsRWJS5g9Icpk9Fm5oWrRgMO/Z
            2Fwp0a28sgUDxqELrKUOV5UGiVhpbZ5aMIHdiSqwJpaS+KEc8fb8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:35:45Z"
    mac: ENC[AES256_GCM,data:vjWvnGIvLjUCeN7AyZRU1H2zMvdFWJ6/lmZcq5gPvnyKnQ+y93Bshg2wz1u41rcq8tnmYxHAAacQB4VOhF6LaWLw4M65+z3wsY0tb0UNTyr1SjNIfov/7GBDdGwL5HZApyQUVeCp8vSGn2r28a3rxhmXhEjL8Jyqz/qPv0YK/dI=,iv:Eaanseeqhx05ALo1lLhiaK5n0Vj1mh8Yyl3gwSULKpA=,tag:9IHd+o1V4xTOe5Y5kfMozA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# Azure Credentials Secret
# To enable Azure cost data, create this secret with your Azure credentials
apiVersion: v1
kind: Secret
metadata:
    name: opencost-azure-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6kun+gNzqJIsF/mtXtj0LpB6bBw+Hw==,iv:1eBO/aKbpNbjE9Qm2vNDZ359VPYa+YnIOB3H34EIJ+A=,tag:V40oufAJQAvXE0+K2nPtww==,type:comment]
    azure_subscription_id: ENC[AES256_GCM,data:M4J43wqZv5E=,iv:/ecxjSP7Mus67LVx0y14GbJDxAToRMB7tkytif/32xM=,tag:mXF6lY+ACdhnGxfJHzI5TA==,type:str]
    #ENC[AES256_GCM,data:ZDr/J5KSxQVIEHSv8Cr5bw==,iv:plLq7BlrVrEw2vsRpn7TV0kv+eTuqW5JimLNK1lcIXA=,tag:uEwbIAhlYfsPxxImwpzH/A==,type:comment]
    azure_tenant_id: ENC[AES256_GCM,data:xwaB1UCZhLQ=,iv:u3LH+2BTbrKP3s98oe/prGGCB+EVoSzoht4eF9SAbac=,tag:elzQNy3QL58k1p1oEEkTdw==,type:str]
    #ENC[AES256_GCM,data:akxa6Ex3BVFOEU95wU42whNW0HUdA/F66NTZLG6WBlE01GnNl1wnTnkonBn74UlxQTty,iv:bMUPWbWvb3Kf/ZA0bQqAiVe1U08uPatkJstx+w2VyrY=,tag:S1k90QDXp5od9NR88CMowA==,type:comment]
    azure_client_id: ENC[AES256_GCM,data:XP91aIvzcls=,iv:yA827dqB6ktkKs9hviF7Sk4XBwpH965kjk9yu91CHuM=,tag:4/Qx8hLvFiuD2CEUKWotLQ==,type:str]
    #ENC[AES256_GCM,data:2Hn5UAOWdiLQZGXMOmRPeuW3yNo0qfLGdv94r8hKOzBygBoVlMRqTPfRB8EuDiDO+MSqDxZii6mX6G0=,iv:Ywj9jInmpVxVo2MUhKkC5YF4psLs4G14V2HJjtM54+Q=,tag:j6S7Ab+3qKs92fYAL/XVsQ==,type:comment]
    azure_client_secret: ENC[AES256_GCM,data:bFMNagH40Xo=,iv:HPVWShcNp4kmtW6wvHrmoY36vQOg7JFahRRmWfD5R+4=,tag:ToSd3VBcbpZT/r+2t+unYQ==,type:str]
    #ENC[AES256_GCM,data:gcXm52BAG5Fmauwkedgzm0YbAozGLO+o3bprcALSaOe16c6WaxWjpzykfKKfxYdx64LpMSldA2oBmoNfxCMNlnI=,iv:kNHgtZ83bv5bNkqX7frExThgwyLyc10VFObWxHCtqFU=,tag:ACvgBhxGHkjqueXlhWd1vg==,type:comment]
    #ENC[AES256_GCM,data:EDXEMNcXWvSEF2GJan7pnjTRJZip0yrouAQXw37VTcygBl0bOxf8cWWb,iv:LDHn9NRs4rMiEevuTkgS0ocEbZWIBum+VE7vIkMis0E=,tag:xxO90b1cNp2VlORE4CZcxQ==,type:comment]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMU9hMEF1TE81TDFsYy8r
            b2tHZ3ZQanVydXV1Uk1nUUdJUDBQTXQ4UkhjCkplUktlajlLN0RKNU5GRVpMenJv
            bzRqSnB2d3dsMDJOeXpNNFRBVVBOSkkKLS0tIDdDNHJrakhWSHloWTB6VHp2ZTFF
            TXpVMm4wc2dyZTB3VEwvdFBCWVFuN1EKbpPZL9PsRWJS5g9Icpk9Fm5oWrRgMO/Z
            2Fwp0a28sgUDxqELrKUOV5UGiVhpbZ5aMIHdiSqwJpaS+KEc8fb8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:35:45Z"
    mac: ENC[AES256_GCM,data:vjWvnGIvLjUCeN7AyZRU1H2zMvdFWJ6/lmZcq5gPvnyKnQ+y93Bshg2wz1u41rcq8tnmYxHAAacQB4VOhF6LaWLw4M65+z3wsY0tb0UNTyr1SjNIfov/7GBDdGwL5HZApyQUVeCp8vSGn2r28a3rxhmXhEjL8Jyqz/qPv0YK/dI=,iv:Eaanseeqhx05ALo1lLhiaK5n0Vj1mh8Yyl3gwSULKpA=,tag:9IHd+o1V4xTOe5Y5kfMozA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# OCI Credentials Secret
# To enable OCI cost data, create this secret with your OCI credentials
apiVersion: v1
kind: Secret
metadata:
    name: opencost-oci-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HDuZFVkUmicXeWOyewG1gFWM,iv:HaNYdsaKTXziZmRTtRXEg9bZ7I8AoPOVeTq7Vc3br74=,tag:pZQfCxf/r3mvsmCcu/pg9g==,type:comment]
    oci_config: ENC[AES256_GCM,data:ks1qVRH20J6S0dKJBqOewSsioS4CXVrVeZvhnCtGTi1kaFzp7jRT1I+fweudwfHWcaWzi0pOeZDqtul90MUQ8k1tw2ITMizQ6l7FhT9dk1L9m9aA7HLDVagNjSgm1ijzOpkMwrgAzNJSn+rvdOe8nBXVDCIZmLTyCAyjCw==,iv:2G/VwHFJnHSH0dQpmq5OfEJIJoyrj9Xy78jOLMclav8=,tag:Sd37Ets/N9NaSMbHwHknDw==,type:str]
    #ENC[AES256_GCM,data:M7tP2ETnkNCpMBDj8yzZC2TdNqU=,iv:GWSvINjMLEUyBATxSHe7Cq7Z8XXSeQetXsTkYDbc5E8=,tag:X6R5J9KGUZ0anHx0fdQw2g==,type:comment]
    oci_api_key.pem: ENC[AES256_GCM,data:fXdVFIiMOTxVHmXfARnsPMRDavpsZYXc3Tr/SN7vtRXPUb+dHX5A3CgZpZl3AK48yHWJWik8VVIb1vh19fsHZF/7Jo2eifw=,iv:rhrzLinNvGVyV/kHxz1fpt3l8vur4zLVBNObbtVEp64=,tag:JC3ICKgmRUjJ09shK0oKnQ==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMU9hMEF1TE81TDFsYy8r
            b2tHZ3ZQanVydXV1Uk1nUUdJUDBQTXQ4UkhjCkplUktlajlLN0RKNU5GRVpMenJv
            bzRqSnB2d3dsMDJOeXpNNFRBVVBOSkkKLS0tIDdDNHJrakhWSHloWTB6VHp2ZTFF
            TXpVMm4wc2dyZTB3VEwvdFBCWVFuN1EKbpPZL9PsRWJS5g9Icpk9Fm5oWrRgMO/Z
            2Fwp0a28sgUDxqELrKUOV5UGiVhpbZ5aMIHdiSqwJpaS+KEc8fb8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:35:45Z"
    mac: ENC[AES256_GCM,data:vjWvnGIvLjUCeN7AyZRU1H2zMvdFWJ6/lmZcq5gPvnyKnQ+y93Bshg2wz1u41rcq8tnmYxHAAacQB4VOhF6LaWLw4M65+z3wsY0tb0UNTyr1SjNIfov/7GBDdGwL5HZApyQUVeCp8vSGn2r28a3rxhmXhEjL8Jyqz/qPv0YK/dI=,iv:Eaanseeqhx05ALo1lLhiaK5n0Vj1mh8Yyl3gwSULKpA=,tag:9IHd+o1V4xTOe5Y5kfMozA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
