# AWS Credentials Secret
# To enable AWS cost data, create this secret with your AWS credentials
apiVersion: v1
kind: Secret
metadata:
    name: opencost-aws-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JAdK7cyYmmikxrE8fNjBJzgQ,iv:HW6uM+hwWDG25b4sh2SCSBVER0eyqkFgX+Pf/k+rxLI=,tag:bbFKj24aDXvYdpOr8rdyww==,type:comment]
    aws_access_key_id: ENC[AES256_GCM,data:WAvuNzXrSYw=,iv:nTIc1xeWaqyCGL3ntNMkBpo2tKfiid8UAcWGnozFxtE=,tag:2jdGHdaDhGl5KgldgctlQg==,type:str]
    #ENC[AES256_GCM,data:jSPOhF3qJuv2BT2++/tqHgf/X1yVsg==,iv:RJ87jgxqwztYhSlfJ5zvKfhXPDkrGXGI8dvpr7hBcJg=,tag:LO50pfP1pzEd/G/o3/rx1w==,type:comment]
    aws_secret_access_key: ENC[AES256_GCM,data:PhI3HD0FV30=,iv:0UT0bg6HcS3bvMhPpvnu6Mx2C7q0k2oDq6CW1DZ9FUg=,tag:QZNwmYss3DImYU28Z4h2og==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcTRLdzBlR01GenVwQWFo
            cHVpOU10YXVqVjBOdjRuL01UTXlscFhvZ1g4CkFRckV5ek9vTlpETFQ5OFdydUJo
            TjFYSTRMYng3UkxmQ3UvblpDeHBoNkkKLS0tIC9hbjY0NkkzNzNJQ1NlZGhGTGpa
            NjNUT2ZESUtUR3NvNFFxb2Vaamp4REEK/l0xO7dws9h5lGFxIxg3I5MfL+o/3F96
            msnjBn8CtmpO5bcIlbYix7izJXvJknwqeTTZmU8KLpY9SurcoN3ruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:02:05Z"
    mac: ENC[AES256_GCM,data:TW+V6U1cxFSEMScpmAT3r1xCKl0j1y650R+elGBQAXS5cFJ7WH8q6wWCie7yNH9w6yYTD2PJ4xMKSCqrnuFX2KTM6S8kZ5kUuCraSytrCm1GQJuPS1rmCtDBrc0vR0qvoVYIUxnqQf2JVQU1lsd9Hjr6VnMLUqRpwHImSWL/5Iw=,iv:rL/r84vcd9X72OKve0nnFyzkb24t74UJCsPQdBpHSSk=,tag:75+oXdnjPfmxjjEiJut5Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# GCP Credentials Secret
# To enable GCP cost data, create this secret with your GCP service account key
apiVersion: v1
kind: Secret
metadata:
    name: opencost-gcp-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ujc8YOPIXS5WO23KAgM2kjAxyecWJqBZK5Y/sNU=,iv:7gQ5TutsRHg8YUG5okBHNHh6ZWMzO04pGjW6eoCvyv0=,tag:bvLgEeqbjpPZG51DKdGs6A==,type:comment]
    gcp_credentials.json: ENC[AES256_GCM,data:1p3693QKsI/cSTYPL27hpVXLN+TgzuqpXxPRabEVP7KZwj0K4f7oM7HCL/Q78/coyWCn5wUN4E5bG3+PTDbvPiJ9BsOCUQQCkkG7+nSrd6wcIgjq5TtUw/3kSfhjD/EJLW5hHo3w8dFs6HDHco8LFh2nM8UccmtXELkW/fjEpu/6HjrRMyZCw+6un+Vl6aaB0kYMRM7vFABV3sNFUpWclyMBbXynEFGY1sRLlx7TYsu2o7VdcIeKT71OC7KxljV4ffVHeqTpnVA+oc91Un9BNsgtHcPBmG3O02ZHpsu2j9Nj2ZE4jCpxX4aHx93ilL/lMc4lzS2xHrbudpctuxk2hF/6uvP7vIxX/bMZ/Rc7FySKsVpFNNFhj+PASAu74VzmWAi8MFw0AEmGRdp9i3ow1n1eGfSm+uV0M6j75COXZIuSMty9UuLuVI71YmQEa8YahMh90gkmUgod/iCxsdRV38avwod3u97l795CKmKm6LdB1qN4Ntxq4yeQnQ3B+vHoHG5SuA0B3LiLjq1h7Bs3i2D1/rdWQkAR,iv:iG4T7o6+LsivLJzdzQ7lEaA1WMIrHrr6bx4kYwXyggA=,tag:ynu8UMg/W36nj4faiPyBGw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcTRLdzBlR01GenVwQWFo
            cHVpOU10YXVqVjBOdjRuL01UTXlscFhvZ1g4CkFRckV5ek9vTlpETFQ5OFdydUJo
            TjFYSTRMYng3UkxmQ3UvblpDeHBoNkkKLS0tIC9hbjY0NkkzNzNJQ1NlZGhGTGpa
            NjNUT2ZESUtUR3NvNFFxb2Vaamp4REEK/l0xO7dws9h5lGFxIxg3I5MfL+o/3F96
            msnjBn8CtmpO5bcIlbYix7izJXvJknwqeTTZmU8KLpY9SurcoN3ruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:02:05Z"
    mac: ENC[AES256_GCM,data:TW+V6U1cxFSEMScpmAT3r1xCKl0j1y650R+elGBQAXS5cFJ7WH8q6wWCie7yNH9w6yYTD2PJ4xMKSCqrnuFX2KTM6S8kZ5kUuCraSytrCm1GQJuPS1rmCtDBrc0vR0qvoVYIUxnqQf2JVQU1lsd9Hjr6VnMLUqRpwHImSWL/5Iw=,iv:rL/r84vcd9X72OKve0nnFyzkb24t74UJCsPQdBpHSSk=,tag:75+oXdnjPfmxjjEiJut5Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# Azure Credentials Secret
# To enable Azure cost data, create this secret with your Azure credentials
apiVersion: v1
kind: Secret
metadata:
    name: opencost-azure-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kNkt5qxlJGlVgtEA1OPTiIUEAV4aIA==,iv:2pKIi8t7ZXWR9xdCOQTWM49I+Z6CY/g3XJ1WwDP2Z6w=,tag:LxuFQP+lpyiBip9Tr5G0AA==,type:comment]
    azure_subscription_id: ENC[AES256_GCM,data:DHYfp1RRn/E=,iv:qfewgqvJsLgN2E5L6O4/QPAnIH7P5s160EeVZYsIaqQ=,tag:FxiDIrKzlnIWVtl90HXFRQ==,type:str]
    #ENC[AES256_GCM,data:nOvjPkAKs2M1WG4rYxGzzg==,iv:H4TVy1a+9XBC6P3zPgjNEEOe8Wk5Xoau+57hMDda1zk=,tag:fHq+ua0JoAKUERPkKfWL+g==,type:comment]
    azure_tenant_id: ENC[AES256_GCM,data:TD9UcWzbdag=,iv:fpVnVmap4sWu720406QrzFJVw7Ny09AxMo+yUxOLKUc=,tag:/WiIj6RHC8Mcp5hkRMaDgQ==,type:str]
    #ENC[AES256_GCM,data:5xB0L1yFHIJXfyOdPkOmDw==,iv:3uEJbJTA/eLQ6pXJBasCEjEYaBuge4bez9Bi09xjSq0=,tag:tmJwXOn+cYMtvHS21j/RVQ==,type:comment]
    azure_client_id: ENC[AES256_GCM,data:frvtBEVjz6M=,iv:FQQb5KzqbVIacMzVVZuFJNr6bzmbBPuJi2xErf3xOmA=,tag:hNQrr2QE7I/vwxMAdclXHg==,type:str]
    #ENC[AES256_GCM,data:y+1n5ZDn6U6Hz/NcmRgX0twZ2zM=,iv:F5QUqFglXKmlNpmF+4OG56F5hMgTPsW9kqJvNyBtdZQ=,tag:aOYwsQnB7aQMV8A4jOp5oA==,type:comment]
    azure_client_secret: ENC[AES256_GCM,data:dnPH0qpmn4Y=,iv:OgYBM24KuVPf4nJOM9EMP3i2jvofJCy1DHX8SZgf1KQ=,tag:MSKrpUlP3bq81zm+HlgFyg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcTRLdzBlR01GenVwQWFo
            cHVpOU10YXVqVjBOdjRuL01UTXlscFhvZ1g4CkFRckV5ek9vTlpETFQ5OFdydUJo
            TjFYSTRMYng3UkxmQ3UvblpDeHBoNkkKLS0tIC9hbjY0NkkzNzNJQ1NlZGhGTGpa
            NjNUT2ZESUtUR3NvNFFxb2Vaamp4REEK/l0xO7dws9h5lGFxIxg3I5MfL+o/3F96
            msnjBn8CtmpO5bcIlbYix7izJXvJknwqeTTZmU8KLpY9SurcoN3ruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:02:05Z"
    mac: ENC[AES256_GCM,data:TW+V6U1cxFSEMScpmAT3r1xCKl0j1y650R+elGBQAXS5cFJ7WH8q6wWCie7yNH9w6yYTD2PJ4xMKSCqrnuFX2KTM6S8kZ5kUuCraSytrCm1GQJuPS1rmCtDBrc0vR0qvoVYIUxnqQf2JVQU1lsd9Hjr6VnMLUqRpwHImSWL/5Iw=,iv:rL/r84vcd9X72OKve0nnFyzkb24t74UJCsPQdBpHSSk=,tag:75+oXdnjPfmxjjEiJut5Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# Azure Cloud Integration Secret (for storage-based cost exports)
# This uses the cloud-integration.json format for reading from Azure Storage
apiVersion: v1
kind: Secret
metadata:
    name: opencost-cloud-integration
    namespace: observability
type: Opaque
stringData:
    cloud-integration.json: ENC[AES256_GCM,data:F1QaklO3GBnU6q++8XCtRNh3li2VzWGrgBUkqW8lBPSIZt5gOPkcdoooaDPVjnwW5Duipe7k/pQ7+XNKuGg6dRFaTNnK1v82GM7uPpie0mXmWltD8SVQTLlXM8xcIEtv2vOfg64sxj14zMUZotJhj1kpTsYJD0Gr1OheJtMGxRehWGA1hqgcu0pWwie9UhQzYoDHLJ99+H+NGbMeSDNoOooC2nknBh73euf1ZkjPyRyBdyAihztqCNLt4g6GXo3as0m87MdeLnwONkD4r8YDa06mGQpvKrhUh7BiAuo0yXch4hVzhLaXXEm5fLhk6Mb4F5oiw1VMRDQxFvHv78NtdxbG1GOXHCB7vtauMlfveXN4M/YfESR/PpOhlqSdTSMYr8bfhgJ3mBbU6p28QHZXMlDZxDWvpsu5hFHOu9XBZFIlR0Hc4j7lOOoWj/Rt9xdyepm4JSjMr+uoTE0UO8H0eb4xZ/q+x4FVcjdI+hGxY92aoWwLTK8NDALOcmnoYjMQpGrLuAS9lFoCCV9rwG09mT/9TT81Yv5EhifJO+TSg20iFPT9ZrU1RKKqBdyxmvN6FwuwIQVfYYOb+PZJ,iv:OjMDlzSCgeyEReFe+bOi08HaurNUgNWCTr00iGvBkTI=,tag:B84fEK3MlsRB67k5eX09Iw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcTRLdzBlR01GenVwQWFo
            cHVpOU10YXVqVjBOdjRuL01UTXlscFhvZ1g4CkFRckV5ek9vTlpETFQ5OFdydUJo
            TjFYSTRMYng3UkxmQ3UvblpDeHBoNkkKLS0tIC9hbjY0NkkzNzNJQ1NlZGhGTGpa
            NjNUT2ZESUtUR3NvNFFxb2Vaamp4REEK/l0xO7dws9h5lGFxIxg3I5MfL+o/3F96
            msnjBn8CtmpO5bcIlbYix7izJXvJknwqeTTZmU8KLpY9SurcoN3ruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:02:05Z"
    mac: ENC[AES256_GCM,data:TW+V6U1cxFSEMScpmAT3r1xCKl0j1y650R+elGBQAXS5cFJ7WH8q6wWCie7yNH9w6yYTD2PJ4xMKSCqrnuFX2KTM6S8kZ5kUuCraSytrCm1GQJuPS1rmCtDBrc0vR0qvoVYIUxnqQf2JVQU1lsd9Hjr6VnMLUqRpwHImSWL/5Iw=,iv:rL/r84vcd9X72OKve0nnFyzkb24t74UJCsPQdBpHSSk=,tag:75+oXdnjPfmxjjEiJut5Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# OCI Credentials Secret
# To enable OCI cost data, create this secret with your OCI credentials
apiVersion: v1
kind: Secret
metadata:
    name: opencost-oci-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:834ptksxdSRn9biEhKi7tg==,iv:EKvjuKJSzs2JVmLPCByuAKbvJYev07s9VpERl9owQKM=,tag:IBv/hEB77HEXBjrKmHw+Nw==,type:comment]
    oci_config: ENC[AES256_GCM,data:qCfdQ+YxHK6tUH86+ZLj2yiP/M9RT1Dp6bNxk0lWWrPGdWrVJULTq2Y+qATktgeWXyLa1wyoPJs8Dal1OtyXgtnkIr0bpXrTwM9o3IUVbtcIKQ239W0ydaasHWLZFIb8kqyLgmbNXctFkrYFeIEuxI6a,iv:55YA8waAqpjq3h+udsWUnKFUUYpn5BsITUMX/GQ3NdQ=,tag:6n/+38higp/nmyBAxEY9cg==,type:str]
    #ENC[AES256_GCM,data:yavQeC7oUl665jL4,iv:kihNBhCn6w+66NQVaPCVOuiNuVvn/Mqw2W9CMDKNIqo=,tag:LGyWQlN6yltKd3UZrnuKig==,type:comment]
    oci_api_key.pem: ENC[AES256_GCM,data:MRm0Om2Fdy9fyEwoS2NLXWaL3pT00JhhC/dcbJok6GUg5OzHmHE930tj1SNYJ13/OA/FRK01mzSWeAlROGd/aE/jZRrka2Q=,iv:ZtajT9Q+1LcQGWsWga8GYm4SQegk8AO7J0lVDqVh1n4=,tag:Vb26v+eeRKpl33sNQjNKEA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcTRLdzBlR01GenVwQWFo
            cHVpOU10YXVqVjBOdjRuL01UTXlscFhvZ1g4CkFRckV5ek9vTlpETFQ5OFdydUJo
            TjFYSTRMYng3UkxmQ3UvblpDeHBoNkkKLS0tIC9hbjY0NkkzNzNJQ1NlZGhGTGpa
            NjNUT2ZESUtUR3NvNFFxb2Vaamp4REEK/l0xO7dws9h5lGFxIxg3I5MfL+o/3F96
            msnjBn8CtmpO5bcIlbYix7izJXvJknwqeTTZmU8KLpY9SurcoN3ruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:02:05Z"
    mac: ENC[AES256_GCM,data:TW+V6U1cxFSEMScpmAT3r1xCKl0j1y650R+elGBQAXS5cFJ7WH8q6wWCie7yNH9w6yYTD2PJ4xMKSCqrnuFX2KTM6S8kZ5kUuCraSytrCm1GQJuPS1rmCtDBrc0vR0qvoVYIUxnqQf2JVQU1lsd9Hjr6VnMLUqRpwHImSWL/5Iw=,iv:rL/r84vcd9X72OKve0nnFyzkb24t74UJCsPQdBpHSSk=,tag:75+oXdnjPfmxjjEiJut5Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
